// Command schema-doc concatenates every SQL migration under
// internal/database/migrations/ into a single deterministic markdown
// document on stdout. The committed docs/SCHEMA.md is the long-lived
// human-readable record of the database schema — a file that keeps
// working even if the Go toolchain stops building in some future year.
//
// Determinism: the output is a pure function of the migration file
// contents and their filenames. No timestamps, no commit SHAs, no git
// calls. This is deliberate — it lets CI run
//
//	make docs && git diff --exit-code docs/SCHEMA.md
//
// to catch a forgotten regen, which would be impossible if any runtime
// metadata leaked into the file. The "when" of a given SCHEMA.md commit
// is recorded in git history; the "what" is its concatenated body.
package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const migrationsDir = "internal/database/migrations"

// Fenced code blocks use FOUR backticks instead of the usual three so a
// migration whose comment happens to contain ``` cannot close the block
// early. GitHub-flavored markdown treats the longer fence as a literal;
// the four-backtick fence is broken only by a run of four-plus backticks,
// which is vanishingly unlikely in SQL.
const (
	fenceOpen  = "````sql\n"
	fenceClose = "\n````\n\n"
)

func main() {
	// Everything is built into a single bytes.Buffer and flushed to stdout
	// in one Write at the end. This is deliberate: `make docs` redirects
	// stdout to docs/SCHEMA.md, and a mid-loop read error in a streaming
	// implementation would leave a half-written file on disk. The
	// buffer-then-single-write path exits non-zero without touching stdout
	// when any input fails, so the committed docs/SCHEMA.md can never be
	// clobbered by a broken run.
	var buf bytes.Buffer
	buf.WriteString("<!-- generated by cmd/schema-doc — do not edit; run `make docs` -->\n")
	buf.WriteString("# SpenDrop Database Schema\n\n")
	buf.WriteString("This file is the concatenation of every migration under ")
	buf.WriteString("`" + migrationsDir + "/`, in lexical order. The migrations ")
	buf.WriteString("ARE the schema — they tell the story of how the database ")
	buf.WriteString("evolved, which a static snapshot cannot.\n\n")
	buf.WriteString("Regenerate with `make docs` after adding a migration.\n\n")

	entries, err := os.ReadDir(migrationsDir)
	if err != nil {
		die("cannot read %s (are you running from the repo root?): %v", migrationsDir, err)
	}
	var names []string
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".sql") {
			names = append(names, e.Name())
		}
	}
	sort.Strings(names)

	if len(names) == 0 {
		// Bootstrap-friendly: a repo with no migrations yet still produces
		// a well-formed SCHEMA.md (and a deterministic one) so CI's drift
		// check keeps working from the very first commit.
		buf.WriteString("_(no migrations present yet)_\n")
	}
	for _, name := range names {
		body, err := os.ReadFile(filepath.Join(migrationsDir, name))
		if err != nil {
			die("read %s: %v", name, err)
		}
		fmt.Fprintf(&buf, "## %s\n\n%s", name, fenceOpen)
		buf.Write(bytes.TrimRight(body, "\n"))
		buf.WriteString(fenceClose)
	}

	if _, err := os.Stdout.Write(buf.Bytes()); err != nil {
		die("write stdout: %v", err)
	}
}

func die(format string, a ...any) {
	fmt.Fprintf(os.Stderr, "schema-doc: "+format+"\n", a...)
	os.Exit(1)
}
