// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type ApiToken struct {
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
	Name        string         `json:"name"`
	TokenHash   string         `json:"token_hash"`
	TokenPrefix string         `json:"token_prefix"`
	ExpiresAt   sql.NullTime   `json:"expires_at"`
	LastUsedAt  sql.NullTime   `json:"last_used_at"`
	LastUsedIp  sql.NullString `json:"last_used_ip"`
	RevokedAt   sql.NullTime   `json:"revoked_at"`
	CreatedAt   time.Time      `json:"created_at"`
}

type ApiTokenAudit struct {
	ID               int64          `json:"id"`
	TokenID          int64          `json:"token_id"`
	UserID           int64          `json:"user_id"`
	Action           string         `json:"action"`
	ActorIp          sql.NullString `json:"actor_ip"`
	ActorUserAgent   sql.NullString `json:"actor_user_agent"`
	ActorSessionHash sql.NullString `json:"actor_session_hash"`
	CreatedAt        time.Time      `json:"created_at"`
}

type AppSetting struct {
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	UpdatedAt time.Time `json:"updated_at"`
}

type BalanceCheckpoint struct {
	ID                     int64          `json:"id"`
	UserID                 int64          `json:"user_id"`
	ScopeType              string         `json:"scope_type"`
	ScopeID                sql.NullInt64  `json:"scope_id"`
	ScopeLabel             sql.NullString `json:"scope_label"`
	Date                   time.Time      `json:"date"`
	ExpectedAmountCents    int64          `json:"expected_amount_cents"`
	Note                   sql.NullString `json:"note"`
	CreatedAt              time.Time      `json:"created_at"`
	LastVerifiedAt         sql.NullTime   `json:"last_verified_at"`
	LastVerificationStatus sql.NullString `json:"last_verification_status"`
}

type Budget struct {
	ID          int64     `json:"id"`
	Year        int64     `json:"year"`
	Month       int64     `json:"month"`
	UpdatedAt   time.Time `json:"updated_at"`
	AmountCents int64     `json:"amount_cents"`
}

type CategoryBudget struct {
	ID          int64     `json:"id"`
	Year        int64     `json:"year"`
	Month       int64     `json:"month"`
	CategoryID  int64     `json:"category_id"`
	AmountCents int64     `json:"amount_cents"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Category struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	Type      string         `json:"type"`
	Icon      sql.NullString `json:"icon"`
	SortOrder int64          `json:"sort_order"`
	IsActive  bool           `json:"is_active"`
	CreatedAt time.Time      `json:"created_at"`
}

type Currency struct {
	Code       string    `json:"code"`
	Name       string    `json:"name"`
	Symbol     string    `json:"symbol"`
	RateToBase float64   `json:"rate_to_base"`
	IsBase     bool      `json:"is_base"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type PushSubscription struct {
	ID        int64          `json:"id"`
	UserID    int64          `json:"user_id"`
	Endpoint  string         `json:"endpoint"`
	P256dh    string         `json:"p256dh"`
	Auth      string         `json:"auth"`
	UserAgent sql.NullString `json:"user_agent"`
	CreatedAt time.Time      `json:"created_at"`
	LastSeen  time.Time      `json:"last_seen"`
}

type SavedFilter struct {
	ID         int64     `json:"id"`
	UserID     int64     `json:"user_id"`
	Name       string    `json:"name"`
	FilterJson string    `json:"filter_json"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type SavingsGoal struct {
	ID                int64     `json:"id"`
	Year              int64     `json:"year"`
	UpdatedAt         time.Time `json:"updated_at"`
	TargetAmountCents int64     `json:"target_amount_cents"`
}

type Session struct {
	Token     string    `json:"token"`
	UserID    int64     `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Transaction struct {
	ID                  int64          `json:"id"`
	UserID              int64          `json:"user_id"`
	Date                time.Time      `json:"date"`
	OriginalCurrency    sql.NullString `json:"original_currency"`
	Description         string         `json:"description"`
	CategoryID          int64          `json:"category_id"`
	Tags                sql.NullString `json:"tags"`
	Notes               sql.NullString `json:"notes"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	DeletedAt           sql.NullTime   `json:"deleted_at"`
	AmountCents         int64          `json:"amount_cents"`
	OriginalAmountCents sql.NullInt64  `json:"original_amount_cents"`
	ContentHash         sql.NullString `json:"content_hash"`
}

type TransactionAudit struct {
	ID            int64          `json:"id"`
	TransactionID int64          `json:"transaction_id"`
	Action        string         `json:"action"`
	ActorUserID   sql.NullInt64  `json:"actor_user_id"`
	OccurredAt    time.Time      `json:"occurred_at"`
	BeforeJson    sql.NullString `json:"before_json"`
	AfterJson     sql.NullString `json:"after_json"`
}

type User struct {
	ID           int64     `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	DisplayName  string    `json:"display_name"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
