// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type AppSetting struct {
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Budget struct {
	ID        int64     `json:"id"`
	Year      int64     `json:"year"`
	Month     int64     `json:"month"`
	Amount    float64   `json:"amount"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Category struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	Type      string         `json:"type"`
	Icon      sql.NullString `json:"icon"`
	SortOrder int64          `json:"sort_order"`
	IsActive  bool           `json:"is_active"`
	CreatedAt time.Time      `json:"created_at"`
}

type Currency struct {
	Code       string    `json:"code"`
	Name       string    `json:"name"`
	Symbol     string    `json:"symbol"`
	RateToBase float64   `json:"rate_to_base"`
	IsBase     bool      `json:"is_base"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type SavedFilter struct {
	ID         int64     `json:"id"`
	UserID     int64     `json:"user_id"`
	Name       string    `json:"name"`
	FilterJson string    `json:"filter_json"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type SavingsGoal struct {
	ID           int64     `json:"id"`
	Year         int64     `json:"year"`
	TargetAmount float64   `json:"target_amount"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Session struct {
	Token     string    `json:"token"`
	UserID    int64     `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Transaction struct {
	ID               int64           `json:"id"`
	UserID           int64           `json:"user_id"`
	Date             time.Time       `json:"date"`
	Amount           float64         `json:"amount"`
	OriginalAmount   sql.NullFloat64 `json:"original_amount"`
	OriginalCurrency sql.NullString  `json:"original_currency"`
	Description      string          `json:"description"`
	CategoryID       int64           `json:"category_id"`
	Tags             sql.NullString  `json:"tags"`
	Notes            sql.NullString  `json:"notes"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
}

type User struct {
	ID           int64     `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"-"`
	DisplayName  string    `json:"display_name"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
