-- IMPORTANT — HAND-MAINTAINED CODEGEN: sqlc cannot generate this repo.
-- `sqlc generate` FAILS here because sqlc's SQLite parser rejects this file's
-- RETURNING clauses and window functions (the report / checkpoint / api-token
-- queries). So queries.sql.go and models.go are edited BY HAND despite their
-- "// Code generated by sqlc. DO NOT EDIT." header — do not trust that header.
-- When you change a query here, hand-edit the matching function + structs in
-- queries.sql.go / models.go to stay in sync (column order, the *Params struct,
-- and the rows.Scan order must match the SELECT/RETURNING column list), then
-- verify with `go build ./...` and `go test ./...`. Note: the Go compiler will
-- NOT catch a wrong column name inside a SQL string literal, so keep every
-- query covered by a test.

-- Users

-- name: CreateUser :one
INSERT INTO users (username, password_hash, display_name, role)
VALUES (?, ?, ?, ?)
RETURNING *;

-- name: GetUserByID :one
SELECT * FROM users WHERE id = ?;

-- name: GetUserByUsername :one
SELECT * FROM users WHERE username = ?;

-- name: ListUsers :many
SELECT * FROM users ORDER BY id;

-- name: UpdateUser :exec
UPDATE users
SET display_name = ?, role = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?;

-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?;

-- name: DeleteUser :execresult
DELETE FROM users WHERE id = ?;

-- Sessions

-- name: CreateSession :exec
INSERT INTO sessions (token, user_id, expires_at)
VALUES (?, ?, ?);

-- name: GetSession :one
SELECT token, user_id, expires_at, created_at
FROM sessions
WHERE token = ?;

-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = ?;

-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < CURRENT_TIMESTAMP;

-- name: DeleteSessionsByUserID :exec
DELETE FROM sessions WHERE user_id = ?;

-- Categories

-- name: CreateCategory :one
INSERT INTO categories (name, type, sort_order)
VALUES (?, ?, ?)
RETURNING *;

-- name: GetCategoryByID :one
SELECT * FROM categories WHERE id = ?;

-- name: ListActiveCategories :many
SELECT * FROM categories WHERE is_active = 1 ORDER BY type, sort_order;

-- name: ListAllCategories :many
SELECT * FROM categories ORDER BY type, sort_order;

-- name: UpdateCategory :execresult
UPDATE categories
SET name = ?, icon = ?
WHERE id = ?;

-- name: UpdateCategorySortOrder :exec
UPDATE categories SET sort_order = ? WHERE id = ?;

-- name: UpdateCategoryActive :execresult
UPDATE categories SET is_active = ? WHERE id = ?;

-- name: DeleteCategory :execresult
DELETE FROM categories WHERE id = ?;

-- Currencies

-- name: ListCurrencies :many
SELECT * FROM currencies;

-- name: GetCurrency :one
SELECT * FROM currencies WHERE code = ?;

-- name: UpsertCurrency :exec
INSERT INTO currencies (code, name, symbol, rate_to_base, is_base)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(code) DO UPDATE SET
    name = excluded.name,
    symbol = excluded.symbol,
    rate_to_base = excluded.rate_to_base,
    is_base = excluded.is_base,
    updated_at = CURRENT_TIMESTAMP;

-- Transactions
--
-- Every read query in this section (and every other transactions read in
-- this file) MUST filter t.deleted_at IS NULL so soft-deleted rows stay
-- hidden from the live app. The only exceptions are:
--   * GetTransactionByID: mutation-only caller (TransactionStore.Update /
--     Delete) needs to see the tombstone row to emit the audit before/after.
--   * ListDeletedTransactions / CountDeletedTransactions: the trash view
--     specifically wants tombstoned rows.
--   * CountAllTransactions: the live/deleted split used by operator tools.
-- When adding a new transactions read, place it in queries.sql (not raw
-- SQL in a handler) and add AND t.deleted_at IS NULL by default.
--
-- Two INTENTIONAL raw reads live OUTSIDE this file and also see tombstones,
-- by design: latestTransactionWriteAt (health_handlers.go) reports the true
-- last-write watermark (a soft-delete is a write that bumps updated_at), and
-- the content_hash backfill pre-count (content_hash.go) must count every
-- un-hashed row including tombstoned ones because the partial unique index
-- idx_transactions_content_hash covers them. Both are deliberate, not
-- invariant violations.

-- name: CreateTransaction :one
-- Phase 3.1b: the legacy REAL columns (amount, original_amount) were dropped
-- in migration 010. Writers populate the INTEGER _cents columns only; the
-- caller computes cents from the float at the wire edge
-- (amount_cents = int64(math.Round(amount*100))).
--
-- Phase 3.4: content_hash is nullable. The import path populates it with
-- SHA-256 over the normalized row (see database.ComputeContentHash); the
-- partial unique index idx_transactions_content_hash then enforces
-- idempotent imports. Manual entries and test fixtures may pass
-- sql.NullString{} — the index ignores NULL rows, so they coexist with
-- hashed import rows without collision.
INSERT INTO transactions (user_id, date, amount_cents, original_amount_cents, original_currency, description, category_id, tags, notes, content_hash)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING *;

-- name: GetTransactionByID :one
-- Mutation-only caller: used by TransactionStore.Update/Delete to emit the
-- audit before/after rows. Deliberately leaks tombstoned rows so Delete can
-- load the live row before marking it deleted_at; the handlers that serve
-- user-facing reads go through ListTransactions / sqlc aggregation queries
-- which all filter deleted_at IS NULL.
SELECT t.*, c.type AS category_type
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE t.id = ?;

-- name: UpdateTransaction :exec
-- Phase 3.1b: the legacy REAL columns were dropped in migration 010; only the
-- INTEGER cents columns are written. The caller computes cents from the float
-- amount before invoking.
UPDATE transactions
SET date = ?, amount_cents = ?, original_amount_cents = ?, original_currency = ?, description = ?, category_id = ?, tags = ?, notes = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?;

-- name: SoftDeleteTransaction :exec
-- Tombstones a live row. The AND deleted_at IS NULL guard makes this
-- idempotent: tombstoning an already-tombstoned row is a no-op and leaves
-- the original deleted_at value intact so the audit trail stays stable.
UPDATE transactions
SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NULL;

-- name: RestoreTransaction :exec
-- Clears the tombstone on a previously soft-deleted row. The
-- AND deleted_at IS NOT NULL guard prevents a restore from silently
-- touching a live row (which would still be a legal UPDATE without the
-- guard, but carries no semantic meaning).
UPDATE transactions
SET deleted_at = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NOT NULL;

-- name: PurgeTransaction :exec
-- Hard delete, used only by the trash purge worker and by operator tools.
-- The AND deleted_at IS NOT NULL guard makes it impossible to purge a
-- live row via this query: the only code path that permanently removes a
-- live row is a full-retention soft-delete-then-purge sequence.
DELETE FROM transactions WHERE id = ? AND deleted_at IS NOT NULL;

-- name: ListDeletedTransactions :many
SELECT t.*, c.name AS category_name, c.type AS category_type
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE t.deleted_at IS NOT NULL
ORDER BY t.deleted_at DESC, t.id DESC
LIMIT ? OFFSET ?;

-- name: CountDeletedTransactions :one
SELECT COUNT(*) FROM transactions WHERE deleted_at IS NOT NULL;

-- name: ListAllDeletedTransactionIDs :many
-- Drives handleRestoreAllTransactions: returns every tombstoned id so the
-- handler can iterate through TransactionStore.RestoreTx, producing one
-- "restore" audit row per id in the same SQL transaction. Ordered by id
-- ASC so the audit log lands in a stable, reproducible order — tests
-- that assert on audit row ordering stay deterministic across SQLite
-- page-cache states.
SELECT id FROM transactions WHERE deleted_at IS NOT NULL ORDER BY id;

-- name: PurgeAllTombstonedTransactions :execresult
-- Single-shot hard delete of every tombstoned row — backs
-- handlePurgeAllTransactions. Unlike the per-row PurgeTransaction this
-- does not iterate, and deliberately writes no audit rows (same
-- asymmetry documented on TransactionStore.Purge: the original delete
-- audit rows plus ON DELETE SET NULL on the FK are the whole audit
-- story). :execresult surfaces sql.Result so the handler can report
-- RowsAffected() back to the caller.
DELETE FROM transactions WHERE deleted_at IS NOT NULL;

-- name: CountAllTransactions :one
SELECT
    CAST(COALESCE(SUM(CASE WHEN deleted_at IS NULL THEN 1 ELSE 0 END), 0) AS INTEGER) AS live,
    CAST(COALESCE(SUM(CASE WHEN deleted_at IS NOT NULL THEN 1 ELSE 0 END), 0) AS INTEGER) AS deleted
FROM transactions;

-- name: GetTransactionByContentHash :one
-- Phase 3.4 import-idempotency lookup. Returns the live row whose content
-- hash matches, or sql.ErrNoRows if none exists. The deleted_at IS NULL
-- filter is deliberate: a tombstoned row with the same hash as a fresh
-- import should NOT block the import (the user previously trashed that
-- row and is now re-adding it, most likely via a spreadsheet re-pull).
-- Without this filter, a user who trashed a row then reimported the
-- spreadsheet would see the row silently dropped with reason "duplicate"
-- — a worse UX than the occasional legitimate double.
--
-- The partial unique index idx_transactions_content_hash guarantees this
-- lookup returns at most one row across the live set, so the :one
-- (exactly-one-or-ErrNoRows) cardinality is safe.
SELECT t.id, t.date, t.amount_cents, t.description, t.category_id, t.content_hash
FROM transactions t
WHERE t.content_hash = ? AND t.deleted_at IS NULL;

-- name: ListTransactionsForHashBackfill :many
-- Phase 3.4 startup backfill. Returns a bounded page of rows whose
-- content_hash is NULL, joined against categories for the name (the
-- hash formula needs category name, not id). The backfill runner pages
-- through this query until it returns zero rows. Tombstoned rows get
-- a hash too — the backfill is a one-shot hygiene pass and we want the
-- audit trail (before_json snapshots) to carry the hash forward. The
-- partial unique index filters `deleted_at IS NULL` so a tombstoned
-- row holding a hash does not block a later re-import of the same
-- content; see migration 008_transactions_content_hash.sql for the
-- full rationale on why the index filter and the lookup filter must
-- agree.
--
-- The `id > ?` cursor pages past rows the backfill has already
-- attempted. When a row's UPDATE would violate the partial unique
-- index (a legitimate same-date/same-amount/same-description duplicate
-- in legacy data), the caller leaves its content_hash NULL and skips
-- it — but without the cursor, that same row would reappear at the
-- head of the next page and the loop would spin forever. The cursor
-- guarantees monotonic progress regardless of whether the UPDATE
-- succeeded or was skipped on UNIQUE.
SELECT t.id, t.date, t.amount_cents, t.description, c.name AS category_name
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE t.content_hash IS NULL AND t.id > ?
ORDER BY t.id
LIMIT ?;

-- name: UpdateTransactionContentHash :exec
-- Phase 3.4 startup backfill writer. Sets content_hash for a single row.
-- No updated_at bump: the backfill is a one-shot schema-hygiene pass,
-- not a user-visible edit, and promoting it into the updated_at stream
-- would make "what did I change yesterday" reports lie.
UPDATE transactions SET content_hash = ? WHERE id = ?;

-- Budgets

-- name: GetBudget :one
SELECT * FROM budgets WHERE year = ? AND month = ?;

-- name: UpsertBudget :exec
-- Phase 3.1b: the legacy REAL amount column was dropped in migration 010;
-- only amount_cents is written. Caller computes cents from the float amount.
INSERT INTO budgets (year, month, amount_cents)
VALUES (?, ?, ?)
ON CONFLICT(year, month) DO UPDATE SET
    amount_cents = excluded.amount_cents,
    updated_at = CURRENT_TIMESTAMP;

-- name: ListBudgetsByYear :many
SELECT * FROM budgets WHERE year = ? ORDER BY month;

-- Category Budgets (Gap 2)
-- Per-category monthly limits. Independent sub-caps; see migration 012 header.
-- sqlc cannot generate this repo (parser fails on RETURNING/window funcs), so
-- the matching Go in queries.sql.go is hand-written, modelled on the Budget
-- funcs above. These statements are kept here for review parity only.

-- name: UpsertCategoryBudget :exec
INSERT INTO category_budgets (year, month, category_id, amount_cents)
VALUES (?, ?, ?, ?)
ON CONFLICT(year, month, category_id) DO UPDATE SET
    amount_cents = excluded.amount_cents,
    updated_at = CURRENT_TIMESTAMP;

-- name: ListCategoryBudgetsByMonth :many
SELECT * FROM category_budgets WHERE year = ? AND month = ? ORDER BY category_id;

-- name: DeleteCategoryBudget :exec
DELETE FROM category_budgets WHERE year = ? AND month = ? AND category_id = ?;

-- Savings Goals

-- name: GetSavingsGoal :one
SELECT * FROM savings_goals WHERE year = ?;

-- name: UpsertSavingsGoal :exec
-- Phase 3.1b: the legacy REAL target_amount column was dropped in migration
-- 010; only target_amount_cents is written. Caller computes cents from the
-- float target amount.
INSERT INTO savings_goals (year, target_amount_cents)
VALUES (?, ?)
ON CONFLICT(year) DO UPDATE SET
    target_amount_cents = excluded.target_amount_cents,
    updated_at = CURRENT_TIMESTAMP;

-- name: ListSavingsGoals :many
SELECT * FROM savings_goals ORDER BY year DESC;

-- App Settings

-- name: GetSetting :one
SELECT * FROM app_settings WHERE key = ?;

-- name: UpsertSetting :exec
INSERT INTO app_settings (key, value)
VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET
    value = excluded.value,
    updated_at = CURRENT_TIMESTAMP;

-- Dashboard aggregation queries
--
-- Phase 3.1a: every aggregation below sums t.amount_cents (int64) instead of
-- t.amount (float64). The result alias is renamed to `*_cents` so the
-- generated Go field is self-documenting and so every consumer at the
-- handler boundary is forced to decide "do I need cents or dollars here?"
-- at the call site rather than trusting float arithmetic implicitly. The
-- CAST(... AS INTEGER) pins the return type - without it sqlc can get
-- confused by SUM() over a nullable integer column.

-- name: SumExpensesByMonth :one
SELECT CAST(COALESCE(SUM(t.amount_cents), 0) AS INTEGER) AS total_cents
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE c.type = 'expense'
    AND t.deleted_at IS NULL
    AND strftime('%Y', t.date) = CAST(sqlc.arg(year) AS TEXT)
    AND strftime('%m', t.date) = CAST(sqlc.arg(month) AS TEXT);

-- name: SumIncomeByMonth :one
SELECT CAST(COALESCE(SUM(t.amount_cents), 0) AS INTEGER) AS total_cents
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE c.type = 'income'
    AND t.deleted_at IS NULL
    AND strftime('%Y', t.date) = CAST(sqlc.arg(year) AS TEXT)
    AND strftime('%m', t.date) = CAST(sqlc.arg(month) AS TEXT);

-- name: SumExpensesByMonthForUser :one
-- User-scoped month total for /api/homepage/summary. Mirrors
-- SumExpensesByMonth exactly but adds t.user_id = ?. Separate from the
-- dashboard query because the dashboard is household-wide (spec §5.3:
-- "summary scoped to token owner"). Soft-delete filter retained inline
-- per .claude/CLAUDE.md soft-delete discipline.
SELECT CAST(COALESCE(SUM(t.amount_cents), 0) AS INTEGER) AS total_cents
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE c.type = 'expense'
    AND t.deleted_at IS NULL
    AND t.user_id = sqlc.arg(user_id)
    AND strftime('%Y', t.date) = CAST(sqlc.arg(year) AS TEXT)
    AND strftime('%m', t.date) = CAST(sqlc.arg(month) AS TEXT);

-- name: CountMonthTransactionsForUser :one
-- User-scoped month-to-date transaction count. Counts BOTH expense and
-- income rows — spec §5.3 defines txn_count as "number of transactions
-- this month," not "number of expenses." Soft-delete filter inline.
SELECT CAST(COUNT(*) AS INTEGER) AS n
FROM transactions t
WHERE t.deleted_at IS NULL
    AND t.user_id = sqlc.arg(user_id)
    AND strftime('%Y', t.date) = CAST(sqlc.arg(year) AS TEXT)
    AND strftime('%m', t.date) = CAST(sqlc.arg(month) AS TEXT);

-- name: SumByCategoryForMonth :many
SELECT c.id, c.name, CAST(COALESCE(SUM(t.amount_cents), 0) AS INTEGER) AS total_cents
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE c.type = 'expense'
    AND t.deleted_at IS NULL
    AND strftime('%Y', t.date) = CAST(sqlc.arg(year) AS TEXT)
    AND strftime('%m', t.date) = CAST(sqlc.arg(month) AS TEXT)
GROUP BY c.id
ORDER BY total_cents DESC;

-- name: SumByMonthRange :many
-- Every t.date comparison below goes through SQLite's date() function so the
-- mattn/go-sqlite3 driver's RFC3339 storage format ("YYYY-MM-DDTHH:MM:SSZ")
-- is normalized to "YYYY-MM-DD" before the lexical compare. Without the
-- wrapper, "2026-04-30T00:00:00Z" <= "2026-04-30" evaluates to FALSE (the
-- "T" sorts after end-of-string), silently dropping transactions dated on
-- the last day of the upper-bound month from every range-scoped report.
-- See reports_metamorphic_test.go for the property-test regression guard.
SELECT
    CAST(strftime('%Y', t.date) AS INTEGER) AS year,
    CAST(strftime('%m', t.date) AS INTEGER) AS month,
    CAST(COALESCE(SUM(CASE WHEN c.type = 'expense' THEN t.amount_cents ELSE 0 END), 0) AS INTEGER) AS expenses_cents,
    CAST(COALESCE(SUM(CASE WHEN c.type = 'income' THEN t.amount_cents ELSE 0 END), 0) AS INTEGER) AS income_cents
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE t.deleted_at IS NULL
    AND date(t.date) >= CAST(sqlc.arg(date_from) AS TEXT) AND date(t.date) <= CAST(sqlc.arg(date_to) AS TEXT)
GROUP BY year, month
ORDER BY year, month;

-- Saved Filters

-- name: CreateSavedFilter :one
INSERT INTO saved_filters (user_id, name, filter_json)
VALUES (?, ?, ?)
RETURNING *;

-- name: ListSavedFilters :many
SELECT * FROM saved_filters WHERE user_id = ? ORDER BY name;

-- name: UpdateSavedFilter :execresult
UPDATE saved_filters SET name = ?, filter_json = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?;

-- name: DeleteSavedFilter :execresult
DELETE FROM saved_filters WHERE id = ? AND user_id = ?;

-- Reports

-- name: SumByCategoryForRange :many
-- date() wrapper normalizes stored RFC3339 dates before lexical compare;
-- see SumByMonthRange above for the full rationale on the month-end bug.
SELECT
    c.id,
    c.name,
    c.type AS category_type,
    CAST(strftime('%Y', t.date) AS INTEGER) AS year,
    CAST(strftime('%m', t.date) AS INTEGER) AS month,
    CAST(COALESCE(SUM(t.amount_cents), 0) AS INTEGER) AS total_cents
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE t.deleted_at IS NULL
    AND date(t.date) >= CAST(sqlc.arg(date_from) AS TEXT) AND date(t.date) <= CAST(sqlc.arg(date_to) AS TEXT)
GROUP BY c.id, year, month
ORDER BY c.name, year, month;

-- name: TopDescriptions :many
-- date() wrapper normalizes stored RFC3339 dates before lexical compare;
-- see SumByMonthRange above for the full rationale on the month-end bug.
-- The c.type = 'expense' predicate is baked in (expense-only surface),
-- so the wrapper protects the range filter without changing the
-- top-level semantics of the query.
SELECT
    t.description,
    c.type AS category_type,
    COUNT(*) AS tx_count,
    CAST(COALESCE(SUM(t.amount_cents), 0) AS INTEGER) AS total_cents
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE c.type = 'expense'
    AND t.deleted_at IS NULL
    AND date(t.date) >= CAST(sqlc.arg(date_from) AS TEXT) AND date(t.date) <= CAST(sqlc.arg(date_to) AS TEXT)
GROUP BY t.description
ORDER BY total_cents DESC
LIMIT sqlc.arg(limit);

-- Spending Heatmap

-- name: SumExpensesByDay :many
SELECT t.date, CAST(COALESCE(SUM(t.amount_cents), 0) AS INTEGER) AS total_cents
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE c.type = 'expense'
    AND t.deleted_at IS NULL
    AND strftime('%Y', t.date) = CAST(sqlc.arg(year) AS TEXT)
GROUP BY t.date
ORDER BY t.date;

-- Expense Velocity

-- name: SumExpensesByDayInMonth :many
SELECT CAST(strftime('%d', t.date) AS INTEGER) AS day,
       CAST(COALESCE(SUM(t.amount_cents), 0) AS INTEGER) AS daily_total_cents
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE c.type = 'expense'
    AND t.deleted_at IS NULL
    AND strftime('%Y', t.date) = CAST(sqlc.arg(year) AS TEXT)
    AND strftime('%m', t.date) = CAST(sqlc.arg(month) AS TEXT)
GROUP BY day
ORDER BY day;

-- Recurring Expenses

-- name: RecurringDescriptions :many
SELECT t.description,
       COUNT(DISTINCT strftime('%Y-%m', t.date)) AS month_count,
       CAST(COALESCE(SUM(t.amount_cents), 0) AS INTEGER) AS annual_total_cents
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE c.type = 'expense'
    AND t.deleted_at IS NULL
    AND strftime('%Y', t.date) = CAST(sqlc.arg(year) AS TEXT)
GROUP BY t.description
HAVING COUNT(DISTINCT strftime('%Y-%m', t.date)) >= 3
ORDER BY annual_total_cents DESC;

-- Tag Breakdown (raw data for Go-side aggregation)

-- name: TransactionAmountsAndTags :many
-- Returns int64 amount_cents instead of float64 amount - Go-side tag
-- aggregation sums cents to avoid float drift, then the handler converts
-- the per-tag totals to dollars at the JSON wire edge.
--
-- date() wrapper normalizes stored RFC3339 dates before lexical compare;
-- see SumByMonthRange above for the full rationale on the month-end bug.
SELECT t.amount_cents, t.tags
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE c.type = 'expense'
    AND t.deleted_at IS NULL
    AND t.tags IS NOT NULL AND t.tags != ''
    AND date(t.date) >= CAST(sqlc.arg(date_from) AS TEXT)
    AND date(t.date) <= CAST(sqlc.arg(date_to) AS TEXT);

-- Transaction Audit Log

-- name: InsertTransactionAudit :exec
INSERT INTO transaction_audit (transaction_id, action, actor_user_id, before_json, after_json)
VALUES (?, ?, ?, ?, ?);

-- name: ListTransactionAuditByID :many
SELECT * FROM transaction_audit
WHERE transaction_id = sqlc.arg(transaction_id)
ORDER BY occurred_at ASC, id ASC
LIMIT sqlc.arg(limit);

-- name: ListRecentTransactionAudit :many
SELECT * FROM transaction_audit
WHERE occurred_at >= CAST(sqlc.arg(since) AS TEXT)
ORDER BY occurred_at DESC, id DESC
LIMIT sqlc.arg(limit);

-- Balance Checkpoints
--
-- Beancount-style assertions of the form: on date D, the scope X summed
-- to Y cents. The verification query is the load-bearing one: it computes
-- the actual sum over live transactions (t.deleted_at IS NULL, Phase 2.1
-- invariant) up to and including the checkpoint date and returns int64
-- cents so the handler can compare against expected_amount_cents without
-- any float coercion. The scope switch is done inline in the WHERE clause
-- so the same query serves all three scope types and sqlc generates a
-- single Go helper.
--
-- Tag-scope note: tags are CSV-encoded in transactions.tags, so tag match
-- uses the canonical CSV-token LIKE pattern. See the long comment on
-- migration 007_balance_checkpoints.sql for the rationale and the exact
-- form of the LIKE expression.

-- name: CreateCheckpoint :one
INSERT INTO balance_checkpoints (
    user_id,
    scope_type,
    scope_id,
    scope_label,
    date,
    expected_amount_cents,
    note,
    last_verification_status
) VALUES (?, ?, ?, ?, ?, ?, ?, 'pending')
RETURNING *;

-- name: GetCheckpoint :one
SELECT * FROM balance_checkpoints WHERE id = ?;

-- name: ListCheckpoints :many
SELECT * FROM balance_checkpoints
ORDER BY date DESC, id DESC;

-- name: ListCheckpointsByUser :many
SELECT * FROM balance_checkpoints
WHERE user_id = ?
ORDER BY date DESC, id DESC;

-- name: DeleteCheckpoint :execresult
DELETE FROM balance_checkpoints WHERE id = ?;

-- name: UpdateCheckpointVerification :exec
UPDATE balance_checkpoints
SET last_verified_at = CURRENT_TIMESTAMP,
    last_verification_status = ?
WHERE id = ?;

-- name: ListCheckpointsAffectedByDate :many
-- Returns every checkpoint whose date is on or after the supplied date.
-- Used by the post-mutation/post-import hook: a transaction with date D
-- can only change the sum-as-of-date for dates greater than or equal to
-- D, so earlier checkpoints are untouchable by definition and skipped.
--
-- The date() wrapper normalizes balance_checkpoints.date before the
-- comparison. Same rationale as the Phase 3.6 fix on SumByMonthRange and
-- friends: sqlc + go-sqlite3 writes time.Time values to DATE columns as
-- RFC3339 ("YYYY-MM-DDTHH:MM:SSZ"), and a lexical compare against a
-- "YYYY-MM-DD" argument string is ACCIDENTALLY safe in the `>=`
-- direction (the 'T' byte sorts after end-of-string) but silently broken
-- for any `<` / `<=` / BETWEEN rewrite. Wrapping with date() pins the
-- semantics at date-only on both sides so the query cannot regress if a
-- future caller flips the inequality.
SELECT * FROM balance_checkpoints
WHERE date(date) >= date(CAST(sqlc.arg(date) AS TEXT))
ORDER BY date ASC, id ASC;

-- name: ListStaleCheckpoints :many
-- Returns checkpoints whose last_verified_at is older than
-- sqlc.arg(threshold) (RFC3339) or NULL. Consumed by /healthz/data to
-- re-verify everything that has drifted beyond the freshness window, so
-- the monitoring scraper carries the cost of periodic re-verification.
SELECT * FROM balance_checkpoints
WHERE last_verified_at IS NULL
   OR last_verified_at < CAST(sqlc.arg(threshold) AS TEXT)
ORDER BY id ASC;

-- name: CountCheckpointsByStatus :one
-- One-row, three-column count used by /healthz/data. NULL status is
-- bucketed into pending so the counts always sum to the total row
-- count of the table.
SELECT
    CAST(COALESCE(SUM(CASE WHEN last_verification_status = 'ok' THEN 1 ELSE 0 END), 0) AS INTEGER) AS ok,
    CAST(COALESCE(SUM(CASE WHEN last_verification_status = 'mismatch' THEN 1 ELSE 0 END), 0) AS INTEGER) AS mismatch,
    CAST(COALESCE(SUM(CASE WHEN last_verification_status = 'pending' OR last_verification_status IS NULL THEN 1 ELSE 0 END), 0) AS INTEGER) AS pending
FROM balance_checkpoints;

-- name: CountStaleMismatchCheckpoints :one
-- Counts mismatched checkpoints whose last_verified_at is older than the
-- supplied threshold. /healthz/data flips to 503 when this is greater than
-- zero, matching the degradation trigger documented in the phase plan.
SELECT CAST(COALESCE(SUM(1), 0) AS INTEGER) AS n
FROM balance_checkpoints
WHERE last_verification_status = 'mismatch'
  AND last_verified_at IS NOT NULL
  AND last_verified_at < CAST(sqlc.arg(threshold) AS TEXT);

-- name: VerifyCheckpointTotal :one
-- The load-bearing verification query. Returns an int64 cents sum over
-- live transactions up to and including the checkpoint date, for the
-- scope matching the supplied arguments. Handler compares the returned
-- actual_cents against the checkpoint expected_amount_cents.
--
-- Phase 2.1: t.deleted_at IS NULL filters tombstoned rows out of the
-- aggregate so a soft-deleted transaction cannot silently flip a
-- previously-verified checkpoint.
-- Phase 3.1a: SUM(t.amount_cents) keeps the aggregate in int64 cents; the
-- COALESCE pins the empty-match case to 0 (not NULL), and the CAST locks
-- sqlc into an int64 return type.
--
-- Phase 3.6: date(t.date) wrapper normalizes the driver's RFC3339 date
-- storage ("YYYY-MM-DDTHH:MM:SSZ") to "YYYY-MM-DD" before the lexical
-- compare. Without the wrapper a transaction dated on the checkpoint day
-- itself would silently drop out of the sum because
-- "2026-04-30T00:00:00Z" <= "2026-04-30" evaluates to FALSE. A verify
-- over a clean set of rows would then return the wrong total and flip
-- the checkpoint to 'mismatch', producing a false alert in /healthz/data.
-- See reports_metamorphic_test.go for the property-test regression guard.
--
-- Every sqlc.arg is wrapped in an explicit CAST so sqlc infers a concrete
-- Go type for every parameter. Without the casts, scope_type lands as
-- interface{} because it is only compared against string literals and
-- scope_id lands as int64 (non-null) which obscures the intent that it
-- is meaningful only when scope_type = 'category'.
SELECT CAST(COALESCE(SUM(t.amount_cents), 0) AS INTEGER) AS actual_cents
FROM transactions t
WHERE t.deleted_at IS NULL
  AND date(t.date) <= CAST(sqlc.arg(date) AS TEXT)
  AND (
    CAST(sqlc.arg(scope_type) AS TEXT) = 'total'
    OR (CAST(sqlc.arg(scope_type) AS TEXT) = 'category' AND t.category_id = CAST(sqlc.arg(scope_id) AS INTEGER))
    OR (CAST(sqlc.arg(scope_type) AS TEXT) = 'tag' AND ',' || COALESCE(t.tags, '') || ',' LIKE '%,' || CAST(sqlc.arg(scope_label) AS TEXT) || ',%')
  );

-- API Tokens
--
-- All writes flow through ApiTokenStore in internal/database/store_api_token.go.
-- Raw calls to these queries in handlers are a bug: they would bypass the
-- paired audit row and break the "every mutation audited" invariant.
--
-- GetAPITokenByHash bakes in the liveness filter (revoked + expiry) so handlers
-- cannot accidentally authenticate with a dead token. Hand-rolling the filter
-- in each handler would rot over time.

-- name: CreateAPIToken :one
INSERT INTO api_tokens (user_id, token_hash, token_prefix, name, expires_at)
VALUES (?, ?, ?, ?, ?)
RETURNING *;

-- name: GetAPITokenByHash :one
-- Returns the live token row matching token_hash, or sql.ErrNoRows. Liveness
-- means NOT revoked AND NOT expired. The middleware relies on this single
-- query to implement "is this token valid" — do not reimplement the filter
-- elsewhere.
SELECT * FROM api_tokens
WHERE token_hash = ?
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > datetime('now'));

-- name: ListLiveAPITokenIDsForUser :many
-- Returns IDs of all live (non-revoked) tokens owned by the user. Used by
-- the store's RevokeAllForUser / RevokeAllForUserTx: they load the ID set
-- first, then UPDATE + emit one audit row per revoked token. Listing first
-- is required because the spec has no sentinel bulk audit row — every
-- revoked token must produce its own `revoked_by_*` audit row against its
-- real id (FK CASCADE means there is no id=0 to pin a summary row to).
SELECT id FROM api_tokens
WHERE user_id = ?
  AND revoked_at IS NULL
ORDER BY id;

-- name: ListAPITokensForUser :many
-- Returns all tokens owned by the user (including revoked), newest first.
-- The Settings UI filters client-side to show only live or only revoked
-- depending on the active tab; listing both in one query keeps the request
-- count down.
SELECT * FROM api_tokens
WHERE user_id = ?
ORDER BY created_at DESC, id DESC;

-- name: ListLiveAPITokensForUser :many
-- Returns full live-token rows for the user: not-revoked AND not-expired.
-- Used by handleListAPITokens (Chunk 4) — the Settings default tab hides
-- revoked/expired rows. ListAPITokensForUser stays for the "include
-- revoked" admin/future view; do not merge them.
SELECT * FROM api_tokens
WHERE user_id = ?
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > datetime('now'))
ORDER BY created_at DESC, id DESC;

-- name: RevokeAPIToken :execrows
-- Revokes a single token owned by user_id. Idempotent: if the token is
-- already revoked, zero rows are affected and the caller treats that as
-- "the user already saw this token was revoked, nothing to do". The
-- ownership check (user_id = ?) prevents a handler bug from letting
-- user A revoke user B's token.
--
-- There is no revoke_reason column on api_tokens — the reason lives in the
-- paired api_token_audit.action (revoked_by_user / revoked_by_password_change
-- / revoked_by_mass_revoke), which is the authoritative record.
UPDATE api_tokens
SET revoked_at = CURRENT_TIMESTAMP
WHERE id = ?
  AND user_id = ?
  AND revoked_at IS NULL;

-- name: RevokeSingleLiveTokenByID :execrows
-- Revokes a single live token by id, no user_id filter. Used only by the
-- store's RevokeAllForUser loop after it has already loaded the ID set
-- filtered by user_id — re-checking ownership inside the loop would be
-- wasted work on a query that only runs with trusted ids. Idempotent on
-- already-revoked rows (affects zero rows) so a concurrent revoke from
-- another session rolls cleanly instead of producing a duplicate audit.
UPDATE api_tokens
SET revoked_at = CURRENT_TIMESTAMP
WHERE id = ?
  AND revoked_at IS NULL;

-- name: TouchAPITokenLastUsed :exec
-- Debounced update: skips the write if last_used_at was touched within the
-- last 60 seconds. This is the Homepage-poll write-amplification fix from
-- spec §3.6 — at a 30s default poll cadence, the write only fires every
-- other poll per token instead of every poll.
--
-- The empty-string IP fold (NULLIF(?, '')) means handlers can pass
-- r.RemoteAddr trimmed or blank without writing "" noise.
UPDATE api_tokens
SET last_used_at = CURRENT_TIMESTAMP,
    last_used_ip = NULLIF(?, '')
WHERE id = ?
  AND (last_used_at IS NULL OR last_used_at < datetime('now', '-60 seconds'));

-- name: InsertAPITokenAudit :exec
-- Writes one audit row per API-token mutation. Column set matches migration
-- 011 exactly:
--   token_id           — FK CASCADE on api_tokens.id (no sentinel bulk id).
--   user_id            — denormalised owner so the user index can scan
--                        an operator's full history in one seek even after
--                        their token rows are hard-deleted by a future
--                        housekeeper (unlikely but cheap insurance).
--   action             — one of the 4 enum values enforced by CHECK.
--   actor_ip           — NULL for system-originated writes (future jobs).
--   actor_user_agent   — truncated to ≤500 chars by the Go caller (CHECK).
--   actor_session_hash — 64-hex SHA-256 of the session cookie, or NULL.
INSERT INTO api_token_audit (
    token_id, user_id, action, actor_ip, actor_user_agent, actor_session_hash
) VALUES (?, ?, ?, ?, ?, ?);

-- name: GetAPITokenByID :one
-- Loads a specific token by id AND user_id. The user_id filter makes the
-- query return sql.ErrNoRows both for "id does not exist" and "id exists
-- but belongs to a different user" — handlers map both to 404, which
-- matches the contract from the user's perspective: tokens they do not
-- own should not be acknowledged even as "revoked".
SELECT * FROM api_tokens
WHERE id = ? AND user_id = ?;

-- name: ListAPITokenAuditByID :many
-- Test/forensic helper: read audit rows for a given token id, oldest-first.
-- Handlers do not call this directly in v1 — the audit UI is out of scope
-- for the token feature — but tests need it and the future audit explorer
-- will too. The idx_api_token_audit_token index covers this access pattern.
SELECT * FROM api_token_audit
WHERE token_id = sqlc.arg(token_id)
ORDER BY created_at ASC, id ASC
LIMIT sqlc.arg(limit);

-- name: ListAPITokenAuditByUser :many
-- Test/forensic helper: read all audit rows for a user across every token
-- they have ever owned, newest-first. Used by the zero-tokens revoke-all
-- test to assert *zero* audit rows were emitted (there is no sentinel row
-- under the new FK CASCADE schema). Matches the idx_api_token_audit_user
-- index (user_id, created_at DESC).
SELECT * FROM api_token_audit
WHERE user_id = sqlc.arg(user_id)
ORDER BY created_at DESC, id DESC
LIMIT sqlc.arg(limit);
