// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const countAllTransactions = `-- name: CountAllTransactions :one
SELECT
    CAST(COALESCE(SUM(CASE WHEN deleted_at IS NULL THEN 1 ELSE 0 END), 0) AS INTEGER) AS live,
    CAST(COALESCE(SUM(CASE WHEN deleted_at IS NOT NULL THEN 1 ELSE 0 END), 0) AS INTEGER) AS deleted
FROM transactions
`

type CountAllTransactionsRow struct {
	Live    int64 `json:"live"`
	Deleted int64 `json:"deleted"`
}

func (q *Queries) CountAllTransactions(ctx context.Context) (CountAllTransactionsRow, error) {
	row := q.db.QueryRowContext(ctx, countAllTransactions)
	var i CountAllTransactionsRow
	err := row.Scan(&i.Live, &i.Deleted)
	return i, err
}

const countCheckpointsByStatus = `-- name: CountCheckpointsByStatus :one
SELECT
    CAST(COALESCE(SUM(CASE WHEN last_verification_status = 'ok' THEN 1 ELSE 0 END), 0) AS INTEGER) AS ok,
    CAST(COALESCE(SUM(CASE WHEN last_verification_status = 'mismatch' THEN 1 ELSE 0 END), 0) AS INTEGER) AS mismatch,
    CAST(COALESCE(SUM(CASE WHEN last_verification_status = 'pending' OR last_verification_status IS NULL THEN 1 ELSE 0 END), 0) AS INTEGER) AS pending
FROM balance_checkpoints
`

type CountCheckpointsByStatusRow struct {
	Ok       int64 `json:"ok"`
	Mismatch int64 `json:"mismatch"`
	Pending  int64 `json:"pending"`
}

// One-row, three-column count used by /healthz/data. NULL status is
// bucketed into pending so the counts always sum to the total row
// count of the table.
func (q *Queries) CountCheckpointsByStatus(ctx context.Context) (CountCheckpointsByStatusRow, error) {
	row := q.db.QueryRowContext(ctx, countCheckpointsByStatus)
	var i CountCheckpointsByStatusRow
	err := row.Scan(&i.Ok, &i.Mismatch, &i.Pending)
	return i, err
}

const countDeletedTransactions = `-- name: CountDeletedTransactions :one
SELECT COUNT(*) FROM transactions WHERE deleted_at IS NOT NULL
`

func (q *Queries) CountDeletedTransactions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeletedTransactions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStaleMismatchCheckpoints = `-- name: CountStaleMismatchCheckpoints :one
SELECT CAST(COALESCE(SUM(1), 0) AS INTEGER) AS n
FROM balance_checkpoints
WHERE last_verification_status = 'mismatch'
  AND last_verified_at IS NOT NULL
  AND last_verified_at < CAST(?1 AS TEXT)
`

// Counts mismatched checkpoints whose last_verified_at is older than the
// supplied threshold. /healthz/data flips to 503 when this is greater than
// zero, matching the degradation trigger documented in the phase plan.
func (q *Queries) CountStaleMismatchCheckpoints(ctx context.Context, threshold string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countStaleMismatchCheckpoints, threshold)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const createCategory = `-- name: CreateCategory :one

INSERT INTO categories (name, type, sort_order)
VALUES (?, ?, ?)
RETURNING id, name, type, icon, sort_order, is_active, created_at
`

type CreateCategoryParams struct {
	Name      string `json:"name"`
	Type      string `json:"type"`
	SortOrder int64  `json:"sort_order"`
}

// Categories
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.Name, arg.Type, arg.SortOrder)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Icon,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createCheckpoint = `-- name: CreateCheckpoint :one

INSERT INTO balance_checkpoints (
    user_id,
    scope_type,
    scope_id,
    scope_label,
    date,
    expected_amount_cents,
    note,
    last_verification_status
) VALUES (?, ?, ?, ?, ?, ?, ?, 'pending')
RETURNING id, user_id, scope_type, scope_id, scope_label, date, expected_amount_cents, note, created_at, last_verified_at, last_verification_status
`

type CreateCheckpointParams struct {
	UserID              int64          `json:"user_id"`
	ScopeType           string         `json:"scope_type"`
	ScopeID             sql.NullInt64  `json:"scope_id"`
	ScopeLabel          sql.NullString `json:"scope_label"`
	Date                time.Time      `json:"date"`
	ExpectedAmountCents int64          `json:"expected_amount_cents"`
	Note                sql.NullString `json:"note"`
}

// Balance Checkpoints
//
// Beancount-style assertions of the form: on date D, the scope X summed
// to Y cents. The verification query is the load-bearing one: it computes
// the actual sum over live transactions (t.deleted_at IS NULL, Phase 2.1
// invariant) up to and including the checkpoint date and returns int64
// cents so the handler can compare against expected_amount_cents without
// any float coercion. The scope switch is done inline in the WHERE clause
// so the same query serves all three scope types and sqlc generates a
// single Go helper.
//
// Tag-scope note: tags are CSV-encoded in transactions.tags, so tag match
// uses the canonical CSV-token LIKE pattern. See the long comment on
// migration 007_balance_checkpoints.sql for the rationale and the exact
// form of the LIKE expression.
func (q *Queries) CreateCheckpoint(ctx context.Context, arg CreateCheckpointParams) (BalanceCheckpoint, error) {
	row := q.db.QueryRowContext(ctx, createCheckpoint,
		arg.UserID,
		arg.ScopeType,
		arg.ScopeID,
		arg.ScopeLabel,
		arg.Date,
		arg.ExpectedAmountCents,
		arg.Note,
	)
	var i BalanceCheckpoint
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ScopeType,
		&i.ScopeID,
		&i.ScopeLabel,
		&i.Date,
		&i.ExpectedAmountCents,
		&i.Note,
		&i.CreatedAt,
		&i.LastVerifiedAt,
		&i.LastVerificationStatus,
	)
	return i, err
}

const createSavedFilter = `-- name: CreateSavedFilter :one

INSERT INTO saved_filters (user_id, name, filter_json)
VALUES (?, ?, ?)
RETURNING id, user_id, name, filter_json, created_at, updated_at
`

type CreateSavedFilterParams struct {
	UserID     int64  `json:"user_id"`
	Name       string `json:"name"`
	FilterJson string `json:"filter_json"`
}

// Saved Filters
func (q *Queries) CreateSavedFilter(ctx context.Context, arg CreateSavedFilterParams) (SavedFilter, error) {
	row := q.db.QueryRowContext(ctx, createSavedFilter, arg.UserID, arg.Name, arg.FilterJson)
	var i SavedFilter
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.FilterJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :exec

INSERT INTO sessions (token, user_id, expires_at)
VALUES (?, ?, ?)
`

type CreateSessionParams struct {
	Token     string    `json:"token"`
	UserID    int64     `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

// Sessions
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.Token, arg.UserID, arg.ExpiresAt)
	return err
}

const createTransaction = `-- name: CreateTransaction :one

INSERT INTO transactions (user_id, date, amount, amount_cents, original_amount, original_amount_cents, original_currency, description, category_id, tags, notes, content_hash)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, date, amount, original_amount, original_currency, description, category_id, tags, notes, created_at, updated_at, deleted_at, amount_cents, original_amount_cents, content_hash
`

type CreateTransactionParams struct {
	UserID              int64           `json:"user_id"`
	Date                time.Time       `json:"date"`
	Amount              float64         `json:"amount"`
	AmountCents         int64           `json:"amount_cents"`
	OriginalAmount      sql.NullFloat64 `json:"original_amount"`
	OriginalAmountCents sql.NullInt64   `json:"original_amount_cents"`
	OriginalCurrency    sql.NullString  `json:"original_currency"`
	Description         string          `json:"description"`
	CategoryID          int64           `json:"category_id"`
	Tags                sql.NullString  `json:"tags"`
	Notes               sql.NullString  `json:"notes"`
	ContentHash         sql.NullString  `json:"content_hash"`
}

// Transactions
//
// Every read query in this section (and every other transactions read in
// this file) MUST filter t.deleted_at IS NULL so soft-deleted rows stay
// hidden from the live app. The only exceptions are:
//   - GetTransactionByID: mutation-only caller (TransactionStore.Update /
//     Delete) needs to see the tombstone row to emit the audit before/after.
//   - ListDeletedTransactions / CountDeletedTransactions: the trash view
//     specifically wants tombstoned rows.
//   - CountAllTransactions: the live/deleted split used by operator tools.
//
// When adding a new transactions read, place it in queries.sql (not raw
// SQL in a handler) and add AND t.deleted_at IS NULL by default.
// Dual-write contract (Phase 3.1a): writers populate BOTH the legacy REAL
// columns (amount, original_amount) AND the new INTEGER _cents columns until
// migration 010 drops the legacy columns. Keep the caller math local -
// amount_cents = int64(math.Round(amount*100)) at the call site.
//
// Phase 3.4: content_hash is nullable. Import callers pass the SHA-256
// over the normalized row (database.ComputeContentHash); manual-entry
// handlers and tests pass sql.NullString{} and the partial unique index
// ignores them.
func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.UserID,
		arg.Date,
		arg.Amount,
		arg.AmountCents,
		arg.OriginalAmount,
		arg.OriginalAmountCents,
		arg.OriginalCurrency,
		arg.Description,
		arg.CategoryID,
		arg.Tags,
		arg.Notes,
		arg.ContentHash,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.Amount,
		&i.OriginalAmount,
		&i.OriginalCurrency,
		&i.Description,
		&i.CategoryID,
		&i.Tags,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AmountCents,
		&i.OriginalAmountCents,
		&i.ContentHash,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (username, password_hash, display_name, role)
VALUES (?, ?, ?, ?)
RETURNING id, username, password_hash, display_name, role, created_at, updated_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	DisplayName  string `json:"display_name"`
	Role         string `json:"role"`
}

// Users
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :execresult
DELETE FROM categories WHERE id = ?
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteCategory, id)
}

const deleteCheckpoint = `-- name: DeleteCheckpoint :execresult
DELETE FROM balance_checkpoints WHERE id = ?
`

func (q *Queries) DeleteCheckpoint(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteCheckpoint, id)
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteSavedFilter = `-- name: DeleteSavedFilter :execresult
DELETE FROM saved_filters WHERE id = ? AND user_id = ?
`

type DeleteSavedFilterParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteSavedFilter(ctx context.Context, arg DeleteSavedFilterParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteSavedFilter, arg.ID, arg.UserID)
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const deleteSessionsByUserID = `-- name: DeleteSessionsByUserID :exec
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteSessionsByUserID(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsByUserID, userID)
	return err
}

const deleteUser = `-- name: DeleteUser :execresult
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUser, id)
}

const getBudget = `-- name: GetBudget :one

SELECT id, year, month, amount, updated_at, amount_cents FROM budgets WHERE year = ? AND month = ?
`

type GetBudgetParams struct {
	Year  int64 `json:"year"`
	Month int64 `json:"month"`
}

// Budgets
func (q *Queries) GetBudget(ctx context.Context, arg GetBudgetParams) (Budget, error) {
	row := q.db.QueryRowContext(ctx, getBudget, arg.Year, arg.Month)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Month,
		&i.Amount,
		&i.UpdatedAt,
		&i.AmountCents,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name, type, icon, sort_order, is_active, created_at FROM categories WHERE id = ?
`

func (q *Queries) GetCategoryByID(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Icon,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getCheckpoint = `-- name: GetCheckpoint :one
SELECT id, user_id, scope_type, scope_id, scope_label, date, expected_amount_cents, note, created_at, last_verified_at, last_verification_status FROM balance_checkpoints WHERE id = ?
`

func (q *Queries) GetCheckpoint(ctx context.Context, id int64) (BalanceCheckpoint, error) {
	row := q.db.QueryRowContext(ctx, getCheckpoint, id)
	var i BalanceCheckpoint
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ScopeType,
		&i.ScopeID,
		&i.ScopeLabel,
		&i.Date,
		&i.ExpectedAmountCents,
		&i.Note,
		&i.CreatedAt,
		&i.LastVerifiedAt,
		&i.LastVerificationStatus,
	)
	return i, err
}

const getCurrency = `-- name: GetCurrency :one
SELECT code, name, symbol, rate_to_base, is_base, updated_at FROM currencies WHERE code = ?
`

func (q *Queries) GetCurrency(ctx context.Context, code string) (Currency, error) {
	row := q.db.QueryRowContext(ctx, getCurrency, code)
	var i Currency
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.RateToBase,
		&i.IsBase,
		&i.UpdatedAt,
	)
	return i, err
}

const getSavingsGoal = `-- name: GetSavingsGoal :one

SELECT id, year, target_amount, updated_at, target_amount_cents FROM savings_goals WHERE year = ?
`

// Savings Goals
func (q *Queries) GetSavingsGoal(ctx context.Context, year int64) (SavingsGoal, error) {
	row := q.db.QueryRowContext(ctx, getSavingsGoal, year)
	var i SavingsGoal
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.TargetAmount,
		&i.UpdatedAt,
		&i.TargetAmountCents,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT token, user_id, expires_at, created_at
FROM sessions
WHERE token = ?
`

func (q *Queries) GetSession(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, token)
	var i Session
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one

SELECT "key", value, updated_at FROM app_settings WHERE key = ?
`

// App Settings
func (q *Queries) GetSetting(ctx context.Context, key string) (AppSetting, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var i AppSetting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const getTransactionByContentHash = `-- name: GetTransactionByContentHash :one
SELECT t.id, t.date, t.amount_cents, t.description, t.category_id, t.content_hash
FROM transactions t
WHERE t.content_hash = ? AND t.deleted_at IS NULL
`

type GetTransactionByContentHashRow struct {
	ID          int64          `json:"id"`
	Date        time.Time      `json:"date"`
	AmountCents int64          `json:"amount_cents"`
	Description string         `json:"description"`
	CategoryID  int64          `json:"category_id"`
	ContentHash sql.NullString `json:"content_hash"`
}

// Phase 3.4 import-idempotency lookup. Returns the live row whose content
// hash matches, or sql.ErrNoRows if none exists. The deleted_at IS NULL
// filter is deliberate: a tombstoned row with the same hash as a fresh
// import should NOT block the import — the user previously trashed that
// row and is now re-adding it, most likely via a spreadsheet re-pull.
// The partial unique index idx_transactions_content_hash guarantees this
// lookup returns at most one row across the live set.
func (q *Queries) GetTransactionByContentHash(ctx context.Context, contentHash sql.NullString) (GetTransactionByContentHashRow, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByContentHash, contentHash)
	var i GetTransactionByContentHashRow
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.AmountCents,
		&i.Description,
		&i.CategoryID,
		&i.ContentHash,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT t.id, t.user_id, t.date, t.amount, t.original_amount, t.original_currency, t.description, t.category_id, t.tags, t.notes, t.created_at, t.updated_at, t.deleted_at, t.amount_cents, t.original_amount_cents, c.type AS category_type
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE t.id = ?
`

type GetTransactionByIDRow struct {
	ID                  int64           `json:"id"`
	UserID              int64           `json:"user_id"`
	Date                time.Time       `json:"date"`
	Amount              float64         `json:"amount"`
	OriginalAmount      sql.NullFloat64 `json:"original_amount"`
	OriginalCurrency    sql.NullString  `json:"original_currency"`
	Description         string          `json:"description"`
	CategoryID          int64           `json:"category_id"`
	Tags                sql.NullString  `json:"tags"`
	Notes               sql.NullString  `json:"notes"`
	CreatedAt           time.Time       `json:"created_at"`
	UpdatedAt           time.Time       `json:"updated_at"`
	DeletedAt           sql.NullTime    `json:"deleted_at"`
	AmountCents         int64           `json:"amount_cents"`
	OriginalAmountCents sql.NullInt64   `json:"original_amount_cents"`
	CategoryType        string          `json:"category_type"`
}

// Mutation-only caller: used by TransactionStore.Update/Delete to emit the
// audit before/after rows. Deliberately leaks tombstoned rows so Delete can
// load the live row before marking it deleted_at; the handlers that serve
// user-facing reads go through ListTransactions / sqlc aggregation queries
// which all filter deleted_at IS NULL.
func (q *Queries) GetTransactionByID(ctx context.Context, id int64) (GetTransactionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByID, id)
	var i GetTransactionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.Amount,
		&i.OriginalAmount,
		&i.OriginalCurrency,
		&i.Description,
		&i.CategoryID,
		&i.Tags,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AmountCents,
		&i.OriginalAmountCents,
		&i.CategoryType,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, display_name, role, created_at, updated_at FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, display_name, role, created_at, updated_at FROM users WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTransactionAudit = `-- name: InsertTransactionAudit :exec

INSERT INTO transaction_audit (transaction_id, action, actor_user_id, before_json, after_json)
VALUES (?, ?, ?, ?, ?)
`

type InsertTransactionAuditParams struct {
	TransactionID int64          `json:"transaction_id"`
	Action        string         `json:"action"`
	ActorUserID   sql.NullInt64  `json:"actor_user_id"`
	BeforeJson    sql.NullString `json:"before_json"`
	AfterJson     sql.NullString `json:"after_json"`
}

// Transaction Audit Log
func (q *Queries) InsertTransactionAudit(ctx context.Context, arg InsertTransactionAuditParams) error {
	_, err := q.db.ExecContext(ctx, insertTransactionAudit,
		arg.TransactionID,
		arg.Action,
		arg.ActorUserID,
		arg.BeforeJson,
		arg.AfterJson,
	)
	return err
}

const listActiveCategories = `-- name: ListActiveCategories :many
SELECT id, name, type, icon, sort_order, is_active, created_at FROM categories WHERE is_active = 1 ORDER BY type, sort_order
`

func (q *Queries) ListActiveCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listActiveCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Icon,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllCategories = `-- name: ListAllCategories :many
SELECT id, name, type, icon, sort_order, is_active, created_at FROM categories ORDER BY type, sort_order
`

func (q *Queries) ListAllCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Icon,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllDeletedTransactionIDs = `-- name: ListAllDeletedTransactionIDs :many
SELECT id FROM transactions WHERE deleted_at IS NOT NULL ORDER BY id
`

// Drives handleRestoreAllTransactions: returns every tombstoned id so the
// handler can iterate through TransactionStore.RestoreTx, producing one
// "restore" audit row per id in the same SQL transaction. Ordered by id
// ASC so the audit log lands in a stable, reproducible order — tests
// that assert on audit row ordering stay deterministic across SQLite
// page-cache states.
func (q *Queries) ListAllDeletedTransactionIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listAllDeletedTransactionIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetsByYear = `-- name: ListBudgetsByYear :many
SELECT id, year, month, amount, updated_at, amount_cents FROM budgets WHERE year = ? ORDER BY month
`

func (q *Queries) ListBudgetsByYear(ctx context.Context, year int64) ([]Budget, error) {
	rows, err := q.db.QueryContext(ctx, listBudgetsByYear, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Budget{}
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.Year,
			&i.Month,
			&i.Amount,
			&i.UpdatedAt,
			&i.AmountCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckpoints = `-- name: ListCheckpoints :many
SELECT id, user_id, scope_type, scope_id, scope_label, date, expected_amount_cents, note, created_at, last_verified_at, last_verification_status FROM balance_checkpoints
ORDER BY date DESC, id DESC
`

func (q *Queries) ListCheckpoints(ctx context.Context) ([]BalanceCheckpoint, error) {
	rows, err := q.db.QueryContext(ctx, listCheckpoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BalanceCheckpoint{}
	for rows.Next() {
		var i BalanceCheckpoint
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ScopeType,
			&i.ScopeID,
			&i.ScopeLabel,
			&i.Date,
			&i.ExpectedAmountCents,
			&i.Note,
			&i.CreatedAt,
			&i.LastVerifiedAt,
			&i.LastVerificationStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckpointsAffectedByDate = `-- name: ListCheckpointsAffectedByDate :many
SELECT id, user_id, scope_type, scope_id, scope_label, date, expected_amount_cents, note, created_at, last_verified_at, last_verification_status FROM balance_checkpoints
WHERE date(date) >= date(CAST(?1 AS TEXT))
ORDER BY date ASC, id ASC
`

// Returns every checkpoint whose date is on or after the supplied date.
// Used by the post-mutation/post-import hook: a transaction with date D
// can only change the sum-as-of-date for dates greater than or equal to
// D, so earlier checkpoints are untouchable by definition and skipped.
//
// The date() wrapper normalizes balance_checkpoints.date before the
// comparison. Same rationale as the Phase 3.6 fix on SumByMonthRange and
// friends: sqlc + go-sqlite3 writes time.Time values to DATE columns as
// RFC3339 ("YYYY-MM-DDTHH:MM:SSZ"), and a lexical compare against a
// "YYYY-MM-DD" argument string is ACCIDENTALLY safe in the `>=`
// direction (the 'T' byte sorts after end-of-string) but silently broken
// for any `<` / `<=` / BETWEEN rewrite. Wrapping with date() pins the
// semantics at date-only on both sides so the query cannot regress if a
// future caller flips the inequality.
func (q *Queries) ListCheckpointsAffectedByDate(ctx context.Context, date string) ([]BalanceCheckpoint, error) {
	rows, err := q.db.QueryContext(ctx, listCheckpointsAffectedByDate, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BalanceCheckpoint{}
	for rows.Next() {
		var i BalanceCheckpoint
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ScopeType,
			&i.ScopeID,
			&i.ScopeLabel,
			&i.Date,
			&i.ExpectedAmountCents,
			&i.Note,
			&i.CreatedAt,
			&i.LastVerifiedAt,
			&i.LastVerificationStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckpointsByUser = `-- name: ListCheckpointsByUser :many
SELECT id, user_id, scope_type, scope_id, scope_label, date, expected_amount_cents, note, created_at, last_verified_at, last_verification_status FROM balance_checkpoints
WHERE user_id = ?
ORDER BY date DESC, id DESC
`

func (q *Queries) ListCheckpointsByUser(ctx context.Context, userID int64) ([]BalanceCheckpoint, error) {
	rows, err := q.db.QueryContext(ctx, listCheckpointsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BalanceCheckpoint{}
	for rows.Next() {
		var i BalanceCheckpoint
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ScopeType,
			&i.ScopeID,
			&i.ScopeLabel,
			&i.Date,
			&i.ExpectedAmountCents,
			&i.Note,
			&i.CreatedAt,
			&i.LastVerifiedAt,
			&i.LastVerificationStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrencies = `-- name: ListCurrencies :many

SELECT code, name, symbol, rate_to_base, is_base, updated_at FROM currencies
`

// Currencies
func (q *Queries) ListCurrencies(ctx context.Context) ([]Currency, error) {
	rows, err := q.db.QueryContext(ctx, listCurrencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Currency{}
	for rows.Next() {
		var i Currency
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Symbol,
			&i.RateToBase,
			&i.IsBase,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedTransactions = `-- name: ListDeletedTransactions :many
SELECT t.id, t.user_id, t.date, t.amount, t.original_amount, t.original_currency, t.description, t.category_id, t.tags, t.notes, t.created_at, t.updated_at, t.deleted_at, t.amount_cents, t.original_amount_cents, c.name AS category_name, c.type AS category_type
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE t.deleted_at IS NOT NULL
ORDER BY t.deleted_at DESC, t.id DESC
LIMIT ? OFFSET ?
`

type ListDeletedTransactionsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListDeletedTransactionsRow struct {
	ID                  int64           `json:"id"`
	UserID              int64           `json:"user_id"`
	Date                time.Time       `json:"date"`
	Amount              float64         `json:"amount"`
	OriginalAmount      sql.NullFloat64 `json:"original_amount"`
	OriginalCurrency    sql.NullString  `json:"original_currency"`
	Description         string          `json:"description"`
	CategoryID          int64           `json:"category_id"`
	Tags                sql.NullString  `json:"tags"`
	Notes               sql.NullString  `json:"notes"`
	CreatedAt           time.Time       `json:"created_at"`
	UpdatedAt           time.Time       `json:"updated_at"`
	DeletedAt           sql.NullTime    `json:"deleted_at"`
	AmountCents         int64           `json:"amount_cents"`
	OriginalAmountCents sql.NullInt64   `json:"original_amount_cents"`
	CategoryName        string          `json:"category_name"`
	CategoryType        string          `json:"category_type"`
}

func (q *Queries) ListDeletedTransactions(ctx context.Context, arg ListDeletedTransactionsParams) ([]ListDeletedTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeletedTransactions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeletedTransactionsRow{}
	for rows.Next() {
		var i ListDeletedTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.Amount,
			&i.OriginalAmount,
			&i.OriginalCurrency,
			&i.Description,
			&i.CategoryID,
			&i.Tags,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.AmountCents,
			&i.OriginalAmountCents,
			&i.CategoryName,
			&i.CategoryType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentTransactionAudit = `-- name: ListRecentTransactionAudit :many
SELECT id, transaction_id, "action", actor_user_id, occurred_at, before_json, after_json FROM transaction_audit
WHERE occurred_at >= CAST(?1 AS TEXT)
ORDER BY occurred_at DESC, id DESC
LIMIT ?2
`

type ListRecentTransactionAuditParams struct {
	Since string `json:"since"`
	Limit int64  `json:"limit"`
}

func (q *Queries) ListRecentTransactionAudit(ctx context.Context, arg ListRecentTransactionAuditParams) ([]TransactionAudit, error) {
	rows, err := q.db.QueryContext(ctx, listRecentTransactionAudit, arg.Since, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransactionAudit{}
	for rows.Next() {
		var i TransactionAudit
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.Action,
			&i.ActorUserID,
			&i.OccurredAt,
			&i.BeforeJson,
			&i.AfterJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedFilters = `-- name: ListSavedFilters :many
SELECT id, user_id, name, filter_json, created_at, updated_at FROM saved_filters WHERE user_id = ? ORDER BY name
`

func (q *Queries) ListSavedFilters(ctx context.Context, userID int64) ([]SavedFilter, error) {
	rows, err := q.db.QueryContext(ctx, listSavedFilters, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavedFilter{}
	for rows.Next() {
		var i SavedFilter
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.FilterJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavingsGoals = `-- name: ListSavingsGoals :many
SELECT id, year, target_amount, updated_at, target_amount_cents FROM savings_goals ORDER BY year DESC
`

func (q *Queries) ListSavingsGoals(ctx context.Context) ([]SavingsGoal, error) {
	rows, err := q.db.QueryContext(ctx, listSavingsGoals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavingsGoal{}
	for rows.Next() {
		var i SavingsGoal
		if err := rows.Scan(
			&i.ID,
			&i.Year,
			&i.TargetAmount,
			&i.UpdatedAt,
			&i.TargetAmountCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleCheckpoints = `-- name: ListStaleCheckpoints :many
SELECT id, user_id, scope_type, scope_id, scope_label, date, expected_amount_cents, note, created_at, last_verified_at, last_verification_status FROM balance_checkpoints
WHERE last_verified_at IS NULL
   OR last_verified_at < CAST(?1 AS TEXT)
ORDER BY id ASC
`

// Returns checkpoints whose last_verified_at is older than
// sqlc.arg(threshold) (RFC3339) or NULL. Consumed by /healthz/data to
// re-verify everything that has drifted beyond the freshness window, so
// the monitoring scraper carries the cost of periodic re-verification.
func (q *Queries) ListStaleCheckpoints(ctx context.Context, threshold string) ([]BalanceCheckpoint, error) {
	rows, err := q.db.QueryContext(ctx, listStaleCheckpoints, threshold)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BalanceCheckpoint{}
	for rows.Next() {
		var i BalanceCheckpoint
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ScopeType,
			&i.ScopeID,
			&i.ScopeLabel,
			&i.Date,
			&i.ExpectedAmountCents,
			&i.Note,
			&i.CreatedAt,
			&i.LastVerifiedAt,
			&i.LastVerificationStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionAuditByID = `-- name: ListTransactionAuditByID :many
SELECT id, transaction_id, "action", actor_user_id, occurred_at, before_json, after_json FROM transaction_audit
WHERE transaction_id = ?1
ORDER BY occurred_at ASC, id ASC
LIMIT ?2
`

type ListTransactionAuditByIDParams struct {
	TransactionID int64 `json:"transaction_id"`
	Limit         int64 `json:"limit"`
}

func (q *Queries) ListTransactionAuditByID(ctx context.Context, arg ListTransactionAuditByIDParams) ([]TransactionAudit, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionAuditByID, arg.TransactionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransactionAudit{}
	for rows.Next() {
		var i TransactionAudit
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.Action,
			&i.ActorUserID,
			&i.OccurredAt,
			&i.BeforeJson,
			&i.AfterJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsForHashBackfill = `-- name: ListTransactionsForHashBackfill :many
SELECT t.id, t.date, t.amount_cents, t.description, c.name AS category_name
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE t.content_hash IS NULL AND t.id > ?
ORDER BY t.id
LIMIT ?
`

type ListTransactionsForHashBackfillParams struct {
	ID    int64 `json:"id"`
	Limit int64 `json:"limit"`
}

type ListTransactionsForHashBackfillRow struct {
	ID           int64     `json:"id"`
	Date         time.Time `json:"date"`
	AmountCents  int64     `json:"amount_cents"`
	Description  string    `json:"description"`
	CategoryName string    `json:"category_name"`
}

// Phase 3.4 startup backfill. Returns a bounded page of rows whose
// content_hash is NULL, joined against categories for the name (the
// hash formula needs category name, not id). The backfill runner pages
// through this query until it returns zero rows. Tombstoned rows get
// a hash too — the filter on content_hash IS NULL does not care about
// deleted_at, because the partial unique index also ignores deleted_at
// and we want the tombstoned row's hash to be stable so a later Restore
// flows through Phase 3.3's checkpoint hook cleanly.
//
// The id cursor (t.id > ?) pages past rows the backfill has already
// attempted. A row left NULL after a UNIQUE-collision skip must not
// reappear at the head of the next page; the cursor makes progress
// monotonic regardless of whether each UPDATE succeeded.
func (q *Queries) ListTransactionsForHashBackfill(ctx context.Context, arg ListTransactionsForHashBackfillParams) ([]ListTransactionsForHashBackfillRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsForHashBackfill, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsForHashBackfillRow{}
	for rows.Next() {
		var i ListTransactionsForHashBackfillRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.AmountCents,
			&i.Description,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password_hash, display_name, role, created_at, updated_at FROM users ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.DisplayName,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeAllTombstonedTransactions = `-- name: PurgeAllTombstonedTransactions :execresult
DELETE FROM transactions WHERE deleted_at IS NOT NULL
`

// Single-shot hard delete of every tombstoned row — backs
// handlePurgeAllTransactions. Unlike the per-row PurgeTransaction this
// does not iterate, and deliberately writes no audit rows (same
// asymmetry documented on TransactionStore.Purge: the original delete
// audit rows plus ON DELETE SET NULL on the FK are the whole audit
// story). :execresult surfaces sql.Result so the handler can report
// RowsAffected() back to the caller.
func (q *Queries) PurgeAllTombstonedTransactions(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, purgeAllTombstonedTransactions)
}

const purgeTransaction = `-- name: PurgeTransaction :exec
DELETE FROM transactions WHERE id = ? AND deleted_at IS NOT NULL
`

// Hard delete, used only by the trash purge worker and by operator tools.
// The AND deleted_at IS NOT NULL guard makes it impossible to purge a
// live row via this query: the only code path that permanently removes a
// live row is a full-retention soft-delete-then-purge sequence.
func (q *Queries) PurgeTransaction(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, purgeTransaction, id)
	return err
}

const recurringDescriptions = `-- name: RecurringDescriptions :many

SELECT t.description,
       COUNT(DISTINCT strftime('%Y-%m', t.date)) AS month_count,
       CAST(COALESCE(SUM(t.amount_cents), 0) AS INTEGER) AS annual_total_cents
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE c.type = 'expense'
    AND t.deleted_at IS NULL
    AND strftime('%Y', t.date) = CAST(?1 AS TEXT)
GROUP BY t.description
HAVING COUNT(DISTINCT strftime('%Y-%m', t.date)) >= 3
ORDER BY annual_total_cents DESC
`

type RecurringDescriptionsRow struct {
	Description      string `json:"description"`
	MonthCount       int64  `json:"month_count"`
	AnnualTotalCents int64  `json:"annual_total_cents"`
}

// Recurring Expenses
func (q *Queries) RecurringDescriptions(ctx context.Context, year string) ([]RecurringDescriptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, recurringDescriptions, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringDescriptionsRow{}
	for rows.Next() {
		var i RecurringDescriptionsRow
		if err := rows.Scan(&i.Description, &i.MonthCount, &i.AnnualTotalCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreTransaction = `-- name: RestoreTransaction :exec
UPDATE transactions
SET deleted_at = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NOT NULL
`

// Clears the tombstone on a previously soft-deleted row. The
// AND deleted_at IS NOT NULL guard prevents a restore from silently
// touching a live row (which would still be a legal UPDATE without the
// guard, but carries no semantic meaning).
func (q *Queries) RestoreTransaction(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, restoreTransaction, id)
	return err
}

const softDeleteTransaction = `-- name: SoftDeleteTransaction :exec
UPDATE transactions
SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at IS NULL
`

// Tombstones a live row. The AND deleted_at IS NULL guard makes this
// idempotent: tombstoning an already-tombstoned row is a no-op and leaves
// the original deleted_at value intact so the audit trail stays stable.
func (q *Queries) SoftDeleteTransaction(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteTransaction, id)
	return err
}

const sumByCategoryForMonth = `-- name: SumByCategoryForMonth :many
SELECT c.id, c.name, CAST(COALESCE(SUM(t.amount_cents), 0) AS INTEGER) AS total_cents
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE c.type = 'expense'
    AND t.deleted_at IS NULL
    AND strftime('%Y', t.date) = CAST(?1 AS TEXT)
    AND strftime('%m', t.date) = CAST(?2 AS TEXT)
GROUP BY c.id
ORDER BY total_cents DESC
`

type SumByCategoryForMonthParams struct {
	Year  string `json:"year"`
	Month string `json:"month"`
}

type SumByCategoryForMonthRow struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	TotalCents int64  `json:"total_cents"`
}

func (q *Queries) SumByCategoryForMonth(ctx context.Context, arg SumByCategoryForMonthParams) ([]SumByCategoryForMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, sumByCategoryForMonth, arg.Year, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumByCategoryForMonthRow{}
	for rows.Next() {
		var i SumByCategoryForMonthRow
		if err := rows.Scan(&i.ID, &i.Name, &i.TotalCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumByCategoryForRange = `-- name: SumByCategoryForRange :many
SELECT
    c.id,
    c.name,
    c.type AS category_type,
    CAST(strftime('%Y', t.date) AS INTEGER) AS year,
    CAST(strftime('%m', t.date) AS INTEGER) AS month,
    CAST(COALESCE(SUM(t.amount_cents), 0) AS INTEGER) AS total_cents
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE t.deleted_at IS NULL
    AND date(t.date) >= CAST(?1 AS TEXT) AND date(t.date) <= CAST(?2 AS TEXT)
GROUP BY c.id, year, month
ORDER BY c.name, year, month
`

type SumByCategoryForRangeParams struct {
	DateFrom string `json:"date_from"`
	DateTo   string `json:"date_to"`
}

type SumByCategoryForRangeRow struct {
	ID           int64  `json:"id"`
	Name         string `json:"name"`
	CategoryType string `json:"category_type"`
	Year         int64  `json:"year"`
	Month        int64  `json:"month"`
	TotalCents   int64  `json:"total_cents"`
}

// Reports
// date() wrapper normalizes stored RFC3339 dates before lexical compare;
// see SumByMonthRange above for the full rationale on the month-end bug.
func (q *Queries) SumByCategoryForRange(ctx context.Context, arg SumByCategoryForRangeParams) ([]SumByCategoryForRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, sumByCategoryForRange, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumByCategoryForRangeRow{}
	for rows.Next() {
		var i SumByCategoryForRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CategoryType,
			&i.Year,
			&i.Month,
			&i.TotalCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumByMonthRange = `-- name: SumByMonthRange :many
SELECT
    CAST(strftime('%Y', t.date) AS INTEGER) AS year,
    CAST(strftime('%m', t.date) AS INTEGER) AS month,
    CAST(COALESCE(SUM(CASE WHEN c.type = 'expense' THEN t.amount_cents ELSE 0 END), 0) AS INTEGER) AS expenses_cents,
    CAST(COALESCE(SUM(CASE WHEN c.type = 'income' THEN t.amount_cents ELSE 0 END), 0) AS INTEGER) AS income_cents
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE t.deleted_at IS NULL
    AND date(t.date) >= CAST(?1 AS TEXT) AND date(t.date) <= CAST(?2 AS TEXT)
GROUP BY year, month
ORDER BY year, month
`

type SumByMonthRangeParams struct {
	DateFrom string `json:"date_from"`
	DateTo   string `json:"date_to"`
}

type SumByMonthRangeRow struct {
	Year          int64 `json:"year"`
	Month         int64 `json:"month"`
	ExpensesCents int64 `json:"expenses_cents"`
	IncomeCents   int64 `json:"income_cents"`
}

// Every t.date comparison below goes through SQLite's date() function so the
// mattn/go-sqlite3 driver's RFC3339 storage format ("YYYY-MM-DDTHH:MM:SSZ")
// is normalized to "YYYY-MM-DD" before the lexical compare. Without the
// wrapper, "2026-04-30T00:00:00Z" <= "2026-04-30" evaluates to FALSE (the
// "T" sorts after end-of-string), silently dropping transactions dated on
// the last day of the upper-bound month from every range-scoped report.
// See reports_metamorphic_test.go for the property-test regression guard.
func (q *Queries) SumByMonthRange(ctx context.Context, arg SumByMonthRangeParams) ([]SumByMonthRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, sumByMonthRange, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumByMonthRangeRow{}
	for rows.Next() {
		var i SumByMonthRangeRow
		if err := rows.Scan(
			&i.Year,
			&i.Month,
			&i.ExpensesCents,
			&i.IncomeCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumExpensesByDay = `-- name: SumExpensesByDay :many

SELECT t.date, CAST(COALESCE(SUM(t.amount_cents), 0) AS INTEGER) AS total_cents
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE c.type = 'expense'
    AND t.deleted_at IS NULL
    AND strftime('%Y', t.date) = CAST(?1 AS TEXT)
GROUP BY t.date
ORDER BY t.date
`

type SumExpensesByDayRow struct {
	Date       time.Time `json:"date"`
	TotalCents int64     `json:"total_cents"`
}

// Spending Heatmap
func (q *Queries) SumExpensesByDay(ctx context.Context, year string) ([]SumExpensesByDayRow, error) {
	rows, err := q.db.QueryContext(ctx, sumExpensesByDay, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumExpensesByDayRow{}
	for rows.Next() {
		var i SumExpensesByDayRow
		if err := rows.Scan(&i.Date, &i.TotalCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumExpensesByDayInMonth = `-- name: SumExpensesByDayInMonth :many

SELECT CAST(strftime('%d', t.date) AS INTEGER) AS day,
       CAST(COALESCE(SUM(t.amount_cents), 0) AS INTEGER) AS daily_total_cents
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE c.type = 'expense'
    AND t.deleted_at IS NULL
    AND strftime('%Y', t.date) = CAST(?1 AS TEXT)
    AND strftime('%m', t.date) = CAST(?2 AS TEXT)
GROUP BY day
ORDER BY day
`

type SumExpensesByDayInMonthParams struct {
	Year  string `json:"year"`
	Month string `json:"month"`
}

type SumExpensesByDayInMonthRow struct {
	Day             int64 `json:"day"`
	DailyTotalCents int64 `json:"daily_total_cents"`
}

// Expense Velocity
func (q *Queries) SumExpensesByDayInMonth(ctx context.Context, arg SumExpensesByDayInMonthParams) ([]SumExpensesByDayInMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, sumExpensesByDayInMonth, arg.Year, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumExpensesByDayInMonthRow{}
	for rows.Next() {
		var i SumExpensesByDayInMonthRow
		if err := rows.Scan(&i.Day, &i.DailyTotalCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumExpensesByMonth = `-- name: SumExpensesByMonth :one

SELECT CAST(COALESCE(SUM(t.amount_cents), 0) AS INTEGER) AS total_cents
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE c.type = 'expense'
    AND t.deleted_at IS NULL
    AND strftime('%Y', t.date) = CAST(?1 AS TEXT)
    AND strftime('%m', t.date) = CAST(?2 AS TEXT)
`

type SumExpensesByMonthParams struct {
	Year  string `json:"year"`
	Month string `json:"month"`
}

// Dashboard aggregation queries
//
// Phase 3.1a: every aggregation below sums t.amount_cents (int64) instead of
// t.amount (float64). The result alias is renamed to `*_cents` so the
// generated Go field is self-documenting and so every consumer at the
// handler boundary is forced to decide "do I need cents or dollars here?"
// at the call site rather than trusting float arithmetic implicitly. The
// CAST(... AS INTEGER) pins the return type - without it sqlc can get
// confused by SUM() over a nullable integer column.
func (q *Queries) SumExpensesByMonth(ctx context.Context, arg SumExpensesByMonthParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumExpensesByMonth, arg.Year, arg.Month)
	var total_cents int64
	err := row.Scan(&total_cents)
	return total_cents, err
}

const sumIncomeByMonth = `-- name: SumIncomeByMonth :one
SELECT CAST(COALESCE(SUM(t.amount_cents), 0) AS INTEGER) AS total_cents
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE c.type = 'income'
    AND t.deleted_at IS NULL
    AND strftime('%Y', t.date) = CAST(?1 AS TEXT)
    AND strftime('%m', t.date) = CAST(?2 AS TEXT)
`

type SumIncomeByMonthParams struct {
	Year  string `json:"year"`
	Month string `json:"month"`
}

func (q *Queries) SumIncomeByMonth(ctx context.Context, arg SumIncomeByMonthParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumIncomeByMonth, arg.Year, arg.Month)
	var total_cents int64
	err := row.Scan(&total_cents)
	return total_cents, err
}

const topDescriptions = `-- name: TopDescriptions :many
SELECT
    t.description,
    c.type AS category_type,
    COUNT(*) AS tx_count,
    CAST(COALESCE(SUM(t.amount_cents), 0) AS INTEGER) AS total_cents
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE c.type = 'expense'
    AND t.deleted_at IS NULL
    AND date(t.date) >= CAST(?1 AS TEXT) AND date(t.date) <= CAST(?2 AS TEXT)
GROUP BY t.description
ORDER BY total_cents DESC
LIMIT ?3
`

type TopDescriptionsParams struct {
	DateFrom string `json:"date_from"`
	DateTo   string `json:"date_to"`
	Limit    int64  `json:"limit"`
}

type TopDescriptionsRow struct {
	Description  string `json:"description"`
	CategoryType string `json:"category_type"`
	TxCount      int64  `json:"tx_count"`
	TotalCents   int64  `json:"total_cents"`
}

// date() wrapper normalizes stored RFC3339 dates before lexical compare;
// see SumByMonthRange above for the full rationale on the month-end bug.
// The c.type = 'expense' predicate is baked in (expense-only surface),
// so the wrapper protects the range filter without changing the
// top-level semantics of the query.
func (q *Queries) TopDescriptions(ctx context.Context, arg TopDescriptionsParams) ([]TopDescriptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, topDescriptions, arg.DateFrom, arg.DateTo, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopDescriptionsRow{}
	for rows.Next() {
		var i TopDescriptionsRow
		if err := rows.Scan(
			&i.Description,
			&i.CategoryType,
			&i.TxCount,
			&i.TotalCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transactionAmountsAndTags = `-- name: TransactionAmountsAndTags :many
SELECT t.amount_cents, t.tags
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE c.type = 'expense'
    AND t.deleted_at IS NULL
    AND t.tags IS NOT NULL AND t.tags != ''
    AND date(t.date) >= CAST(?1 AS TEXT)
    AND date(t.date) <= CAST(?2 AS TEXT)
`

type TransactionAmountsAndTagsParams struct {
	DateFrom string `json:"date_from"`
	DateTo   string `json:"date_to"`
}

type TransactionAmountsAndTagsRow struct {
	AmountCents int64          `json:"amount_cents"`
	Tags        sql.NullString `json:"tags"`
}

// Tag Breakdown (raw data for Go-side aggregation)
// Returns int64 amount_cents instead of float64 amount - Go-side tag
// aggregation sums cents to avoid float drift, then the handler converts
// the per-tag totals to dollars at the JSON wire edge.
//
// date() wrapper normalizes stored RFC3339 dates before lexical compare;
// see SumByMonthRange above for the full rationale on the month-end bug.
func (q *Queries) TransactionAmountsAndTags(ctx context.Context, arg TransactionAmountsAndTagsParams) ([]TransactionAmountsAndTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, transactionAmountsAndTags, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransactionAmountsAndTagsRow{}
	for rows.Next() {
		var i TransactionAmountsAndTagsRow
		if err := rows.Scan(&i.AmountCents, &i.Tags); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :execresult
UPDATE categories
SET name = ?, icon = ?
WHERE id = ?
`

type UpdateCategoryParams struct {
	Name string         `json:"name"`
	Icon sql.NullString `json:"icon"`
	ID   int64          `json:"id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateCategory, arg.Name, arg.Icon, arg.ID)
}

const updateCategoryActive = `-- name: UpdateCategoryActive :execresult
UPDATE categories SET is_active = ? WHERE id = ?
`

type UpdateCategoryActiveParams struct {
	IsActive bool  `json:"is_active"`
	ID       int64 `json:"id"`
}

func (q *Queries) UpdateCategoryActive(ctx context.Context, arg UpdateCategoryActiveParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateCategoryActive, arg.IsActive, arg.ID)
}

const updateCategorySortOrder = `-- name: UpdateCategorySortOrder :exec
UPDATE categories SET sort_order = ? WHERE id = ?
`

type UpdateCategorySortOrderParams struct {
	SortOrder int64 `json:"sort_order"`
	ID        int64 `json:"id"`
}

func (q *Queries) UpdateCategorySortOrder(ctx context.Context, arg UpdateCategorySortOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateCategorySortOrder, arg.SortOrder, arg.ID)
	return err
}

const updateCheckpointVerification = `-- name: UpdateCheckpointVerification :exec
UPDATE balance_checkpoints
SET last_verified_at = CURRENT_TIMESTAMP,
    last_verification_status = ?
WHERE id = ?
`

type UpdateCheckpointVerificationParams struct {
	LastVerificationStatus sql.NullString `json:"last_verification_status"`
	ID                     int64          `json:"id"`
}

func (q *Queries) UpdateCheckpointVerification(ctx context.Context, arg UpdateCheckpointVerificationParams) error {
	_, err := q.db.ExecContext(ctx, updateCheckpointVerification, arg.LastVerificationStatus, arg.ID)
	return err
}

const updateSavedFilter = `-- name: UpdateSavedFilter :execresult
UPDATE saved_filters SET name = ?, filter_json = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
`

type UpdateSavedFilterParams struct {
	Name       string `json:"name"`
	FilterJson string `json:"filter_json"`
	ID         int64  `json:"id"`
	UserID     int64  `json:"user_id"`
}

func (q *Queries) UpdateSavedFilter(ctx context.Context, arg UpdateSavedFilterParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateSavedFilter,
		arg.Name,
		arg.FilterJson,
		arg.ID,
		arg.UserID,
	)
}

const updateTransaction = `-- name: UpdateTransaction :exec
UPDATE transactions
SET date = ?, amount = ?, amount_cents = ?, original_amount = ?, original_amount_cents = ?, original_currency = ?, description = ?, category_id = ?, tags = ?, notes = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateTransactionParams struct {
	Date                time.Time       `json:"date"`
	Amount              float64         `json:"amount"`
	AmountCents         int64           `json:"amount_cents"`
	OriginalAmount      sql.NullFloat64 `json:"original_amount"`
	OriginalAmountCents sql.NullInt64   `json:"original_amount_cents"`
	OriginalCurrency    sql.NullString  `json:"original_currency"`
	Description         string          `json:"description"`
	CategoryID          int64           `json:"category_id"`
	Tags                sql.NullString  `json:"tags"`
	Notes               sql.NullString  `json:"notes"`
	ID                  int64           `json:"id"`
}

// Dual-write contract (Phase 3.1a): see CreateTransaction above. Both the
// legacy REAL column and the new INTEGER cents column are rewritten on every
// edit. The caller computes cents from the float amount before invoking.
//
// Phase 3.4 note: UpdateTransaction deliberately does NOT touch content_hash.
// An edited row keeps the hash it was imported with, so a reimport of the
// source spreadsheet still detects the edited row as a duplicate rather than
// silently doubling it.
func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) error {
	_, err := q.db.ExecContext(ctx, updateTransaction,
		arg.Date,
		arg.Amount,
		arg.AmountCents,
		arg.OriginalAmount,
		arg.OriginalAmountCents,
		arg.OriginalCurrency,
		arg.Description,
		arg.CategoryID,
		arg.Tags,
		arg.Notes,
		arg.ID,
	)
	return err
}

const updateTransactionContentHash = `-- name: UpdateTransactionContentHash :exec
UPDATE transactions SET content_hash = ? WHERE id = ?
`

type UpdateTransactionContentHashParams struct {
	ContentHash sql.NullString `json:"content_hash"`
	ID          int64          `json:"id"`
}

// Phase 3.4 startup backfill writer. Sets content_hash for a single row.
// No updated_at bump: the backfill is a one-shot schema-hygiene pass, not
// a user-visible edit, and promoting it into the updated_at stream would
// make "what did I change yesterday" reports lie.
func (q *Queries) UpdateTransactionContentHash(ctx context.Context, arg UpdateTransactionContentHashParams) error {
	_, err := q.db.ExecContext(ctx, updateTransactionContentHash, arg.ContentHash, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET display_name = ?, role = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateUserParams struct {
	DisplayName string `json:"display_name"`
	Role        string `json:"role"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser, arg.DisplayName, arg.Role, arg.ID)
	return err
}

const upsertBudget = `-- name: UpsertBudget :exec
INSERT INTO budgets (year, month, amount, amount_cents)
VALUES (?, ?, ?, ?)
ON CONFLICT(year, month) DO UPDATE SET
    amount = excluded.amount,
    amount_cents = excluded.amount_cents,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertBudgetParams struct {
	Year        int64   `json:"year"`
	Month       int64   `json:"month"`
	Amount      float64 `json:"amount"`
	AmountCents int64   `json:"amount_cents"`
}

// Dual-write contract (Phase 3.1a): see CreateTransaction. Both the legacy
// REAL column and the new INTEGER cents column are populated on every
// upsert. Caller computes cents from the float amount.
func (q *Queries) UpsertBudget(ctx context.Context, arg UpsertBudgetParams) error {
	_, err := q.db.ExecContext(ctx, upsertBudget,
		arg.Year,
		arg.Month,
		arg.Amount,
		arg.AmountCents,
	)
	return err
}

const upsertCurrency = `-- name: UpsertCurrency :exec
INSERT INTO currencies (code, name, symbol, rate_to_base, is_base)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(code) DO UPDATE SET
    name = excluded.name,
    symbol = excluded.symbol,
    rate_to_base = excluded.rate_to_base,
    is_base = excluded.is_base,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertCurrencyParams struct {
	Code       string  `json:"code"`
	Name       string  `json:"name"`
	Symbol     string  `json:"symbol"`
	RateToBase float64 `json:"rate_to_base"`
	IsBase     bool    `json:"is_base"`
}

func (q *Queries) UpsertCurrency(ctx context.Context, arg UpsertCurrencyParams) error {
	_, err := q.db.ExecContext(ctx, upsertCurrency,
		arg.Code,
		arg.Name,
		arg.Symbol,
		arg.RateToBase,
		arg.IsBase,
	)
	return err
}

const upsertSavingsGoal = `-- name: UpsertSavingsGoal :exec
INSERT INTO savings_goals (year, target_amount, target_amount_cents)
VALUES (?, ?, ?)
ON CONFLICT(year) DO UPDATE SET
    target_amount = excluded.target_amount,
    target_amount_cents = excluded.target_amount_cents,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertSavingsGoalParams struct {
	Year              int64   `json:"year"`
	TargetAmount      float64 `json:"target_amount"`
	TargetAmountCents int64   `json:"target_amount_cents"`
}

// Dual-write contract (Phase 3.1a): see CreateTransaction. Both the legacy
// REAL column and the new INTEGER cents column are populated on every
// upsert. Caller computes cents from the float target amount.
func (q *Queries) UpsertSavingsGoal(ctx context.Context, arg UpsertSavingsGoalParams) error {
	_, err := q.db.ExecContext(ctx, upsertSavingsGoal, arg.Year, arg.TargetAmount, arg.TargetAmountCents)
	return err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO app_settings (key, value)
VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET
    value = excluded.value,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting, arg.Key, arg.Value)
	return err
}

const verifyCheckpointTotal = `-- name: VerifyCheckpointTotal :one
SELECT CAST(COALESCE(SUM(t.amount_cents), 0) AS INTEGER) AS actual_cents
FROM transactions t
WHERE t.deleted_at IS NULL
  AND date(t.date) <= CAST(?1 AS TEXT)
  AND (
    CAST(?2 AS TEXT) = 'total'
    OR (CAST(?2 AS TEXT) = 'category' AND t.category_id = CAST(?3 AS INTEGER))
    OR (CAST(?2 AS TEXT) = 'tag' AND ',' || COALESCE(t.tags, '') || ',' LIKE '%,' || CAST(?4 AS TEXT) || ',%')
  )
`

type VerifyCheckpointTotalParams struct {
	Date       string `json:"date"`
	ScopeType  string `json:"scope_type"`
	ScopeID    int64  `json:"scope_id"`
	ScopeLabel string `json:"scope_label"`
}

// The load-bearing verification query. Returns an int64 cents sum over
// live transactions up to and including the checkpoint date, for the
// scope matching the supplied arguments. Handler compares the returned
// actual_cents against the checkpoint expected_amount_cents.
//
// Phase 2.1: t.deleted_at IS NULL filters tombstoned rows out of the
// aggregate so a soft-deleted transaction cannot silently flip a
// previously-verified checkpoint.
// Phase 3.1a: SUM(t.amount_cents) keeps the aggregate in int64 cents; the
// COALESCE pins the empty-match case to 0 (not NULL), and the CAST locks
// sqlc into an int64 return type.
//
// Phase 3.6: date(t.date) wrapper normalizes the driver's RFC3339 date
// storage ("YYYY-MM-DDTHH:MM:SSZ") to "YYYY-MM-DD" before the lexical
// compare. Without the wrapper a transaction dated on the checkpoint day
// itself would silently drop out of the sum because
// "2026-04-30T00:00:00Z" <= "2026-04-30" evaluates to FALSE. A verify
// over a clean set of rows would then return the wrong total and flip
// the checkpoint to 'mismatch', producing a false alert in /healthz/data.
// See reports_metamorphic_test.go for the property-test regression guard.
//
// Every sqlc.arg is wrapped in an explicit CAST so sqlc infers a concrete
// Go type for every parameter. Without the casts, scope_type lands as
// interface{} because it is only compared against string literals and
// scope_id lands as int64 (non-null) which obscures the intent that it
// is meaningful only when scope_type = 'category'.
func (q *Queries) VerifyCheckpointTotal(ctx context.Context, arg VerifyCheckpointTotalParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, verifyCheckpointTotal,
		arg.Date,
		arg.ScopeType,
		arg.ScopeID,
		arg.ScopeLabel,
	)
	var actual_cents int64
	err := row.Scan(&actual_cents)
	return actual_cents, err
}
