// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createCategory = `-- name: CreateCategory :one

INSERT INTO categories (name, type, sort_order)
VALUES (?, ?, ?)
RETURNING id, name, type, icon, sort_order, is_active, created_at
`

type CreateCategoryParams struct {
	Name      string `json:"name"`
	Type      string `json:"type"`
	SortOrder int64  `json:"sort_order"`
}

// Categories
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.Name, arg.Type, arg.SortOrder)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Icon,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createSavedFilter = `-- name: CreateSavedFilter :one

INSERT INTO saved_filters (user_id, name, filter_json)
VALUES (?, ?, ?)
RETURNING id, user_id, name, filter_json, created_at, updated_at
`

type CreateSavedFilterParams struct {
	UserID     int64  `json:"user_id"`
	Name       string `json:"name"`
	FilterJson string `json:"filter_json"`
}

// Saved Filters
func (q *Queries) CreateSavedFilter(ctx context.Context, arg CreateSavedFilterParams) (SavedFilter, error) {
	row := q.db.QueryRowContext(ctx, createSavedFilter, arg.UserID, arg.Name, arg.FilterJson)
	var i SavedFilter
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.FilterJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :exec

INSERT INTO sessions (token, user_id, expires_at)
VALUES (?, ?, ?)
`

type CreateSessionParams struct {
	Token     string    `json:"token"`
	UserID    int64     `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

// Sessions
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.Token, arg.UserID, arg.ExpiresAt)
	return err
}

const createTransaction = `-- name: CreateTransaction :one

INSERT INTO transactions (user_id, date, amount, original_amount, original_currency, description, category_id, tags, notes)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, date, amount, original_amount, original_currency, description, category_id, tags, notes, created_at, updated_at
`

type CreateTransactionParams struct {
	UserID           int64           `json:"user_id"`
	Date             time.Time       `json:"date"`
	Amount           float64         `json:"amount"`
	OriginalAmount   sql.NullFloat64 `json:"original_amount"`
	OriginalCurrency sql.NullString  `json:"original_currency"`
	Description      string          `json:"description"`
	CategoryID       int64           `json:"category_id"`
	Tags             sql.NullString  `json:"tags"`
	Notes            sql.NullString  `json:"notes"`
}

// Transactions
func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.UserID,
		arg.Date,
		arg.Amount,
		arg.OriginalAmount,
		arg.OriginalCurrency,
		arg.Description,
		arg.CategoryID,
		arg.Tags,
		arg.Notes,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.Amount,
		&i.OriginalAmount,
		&i.OriginalCurrency,
		&i.Description,
		&i.CategoryID,
		&i.Tags,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (username, password_hash, display_name, role)
VALUES (?, ?, ?, ?)
RETURNING id, username, password_hash, display_name, role, created_at, updated_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	DisplayName  string `json:"display_name"`
	Role         string `json:"role"`
}

// Users
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :execresult
DELETE FROM categories WHERE id = ?
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteCategory, id)
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteSavedFilter = `-- name: DeleteSavedFilter :execresult
DELETE FROM saved_filters WHERE id = ? AND user_id = ?
`

type DeleteSavedFilterParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteSavedFilter(ctx context.Context, arg DeleteSavedFilterParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteSavedFilter, arg.ID, arg.UserID)
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const deleteSessionsByUserID = `-- name: DeleteSessionsByUserID :exec
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteSessionsByUserID(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsByUserID, userID)
	return err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions WHERE id = ?
`

func (q *Queries) DeleteTransaction(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTransaction, id)
	return err
}

const deleteUser = `-- name: DeleteUser :execresult
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUser, id)
}

const getBudget = `-- name: GetBudget :one

SELECT id, year, month, amount, updated_at FROM budgets WHERE year = ? AND month = ?
`

type GetBudgetParams struct {
	Year  int64 `json:"year"`
	Month int64 `json:"month"`
}

// Budgets
func (q *Queries) GetBudget(ctx context.Context, arg GetBudgetParams) (Budget, error) {
	row := q.db.QueryRowContext(ctx, getBudget, arg.Year, arg.Month)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Month,
		&i.Amount,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name, type, icon, sort_order, is_active, created_at FROM categories WHERE id = ?
`

func (q *Queries) GetCategoryByID(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Icon,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrency = `-- name: GetCurrency :one
SELECT code, name, symbol, rate_to_base, is_base, updated_at FROM currencies WHERE code = ?
`

func (q *Queries) GetCurrency(ctx context.Context, code string) (Currency, error) {
	row := q.db.QueryRowContext(ctx, getCurrency, code)
	var i Currency
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.RateToBase,
		&i.IsBase,
		&i.UpdatedAt,
	)
	return i, err
}

const getSavingsGoal = `-- name: GetSavingsGoal :one

SELECT id, year, target_amount, updated_at FROM savings_goals WHERE year = ?
`

// Savings Goals
func (q *Queries) GetSavingsGoal(ctx context.Context, year int64) (SavingsGoal, error) {
	row := q.db.QueryRowContext(ctx, getSavingsGoal, year)
	var i SavingsGoal
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.TargetAmount,
		&i.UpdatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT token, user_id, expires_at, created_at
FROM sessions
WHERE token = ?
`

func (q *Queries) GetSession(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, token)
	var i Session
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one

SELECT "key", value, updated_at FROM app_settings WHERE key = ?
`

// App Settings
func (q *Queries) GetSetting(ctx context.Context, key string) (AppSetting, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var i AppSetting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT t.id, t.user_id, t.date, t.amount, t.original_amount, t.original_currency, t.description, t.category_id, t.tags, t.notes, t.created_at, t.updated_at, c.type AS category_type
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE t.id = ?
`

type GetTransactionByIDRow struct {
	ID               int64           `json:"id"`
	UserID           int64           `json:"user_id"`
	Date             time.Time       `json:"date"`
	Amount           float64         `json:"amount"`
	OriginalAmount   sql.NullFloat64 `json:"original_amount"`
	OriginalCurrency sql.NullString  `json:"original_currency"`
	Description      string          `json:"description"`
	CategoryID       int64           `json:"category_id"`
	Tags             sql.NullString  `json:"tags"`
	Notes            sql.NullString  `json:"notes"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
	CategoryType     string          `json:"category_type"`
}

func (q *Queries) GetTransactionByID(ctx context.Context, id int64) (GetTransactionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByID, id)
	var i GetTransactionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.Amount,
		&i.OriginalAmount,
		&i.OriginalCurrency,
		&i.Description,
		&i.CategoryID,
		&i.Tags,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryType,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, display_name, role, created_at, updated_at FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, display_name, role, created_at, updated_at FROM users WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveCategories = `-- name: ListActiveCategories :many
SELECT id, name, type, icon, sort_order, is_active, created_at FROM categories WHERE is_active = 1 ORDER BY type, sort_order
`

func (q *Queries) ListActiveCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listActiveCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Icon,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllCategories = `-- name: ListAllCategories :many
SELECT id, name, type, icon, sort_order, is_active, created_at FROM categories ORDER BY type, sort_order
`

func (q *Queries) ListAllCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Icon,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetsByYear = `-- name: ListBudgetsByYear :many
SELECT id, year, month, amount, updated_at FROM budgets WHERE year = ? ORDER BY month
`

func (q *Queries) ListBudgetsByYear(ctx context.Context, year int64) ([]Budget, error) {
	rows, err := q.db.QueryContext(ctx, listBudgetsByYear, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Budget{}
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.Year,
			&i.Month,
			&i.Amount,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrencies = `-- name: ListCurrencies :many

SELECT code, name, symbol, rate_to_base, is_base, updated_at FROM currencies
`

// Currencies
func (q *Queries) ListCurrencies(ctx context.Context) ([]Currency, error) {
	rows, err := q.db.QueryContext(ctx, listCurrencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Currency{}
	for rows.Next() {
		var i Currency
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Symbol,
			&i.RateToBase,
			&i.IsBase,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedFilters = `-- name: ListSavedFilters :many
SELECT id, user_id, name, filter_json, created_at, updated_at FROM saved_filters WHERE user_id = ? ORDER BY name
`

func (q *Queries) ListSavedFilters(ctx context.Context, userID int64) ([]SavedFilter, error) {
	rows, err := q.db.QueryContext(ctx, listSavedFilters, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavedFilter{}
	for rows.Next() {
		var i SavedFilter
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.FilterJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavingsGoals = `-- name: ListSavingsGoals :many
SELECT id, year, target_amount, updated_at FROM savings_goals ORDER BY year DESC
`

func (q *Queries) ListSavingsGoals(ctx context.Context) ([]SavingsGoal, error) {
	rows, err := q.db.QueryContext(ctx, listSavingsGoals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavingsGoal{}
	for rows.Next() {
		var i SavingsGoal
		if err := rows.Scan(
			&i.ID,
			&i.Year,
			&i.TargetAmount,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password_hash, display_name, role, created_at, updated_at FROM users ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.DisplayName,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recurringDescriptions = `-- name: RecurringDescriptions :many

SELECT t.description,
       COUNT(DISTINCT strftime('%Y-%m', t.date)) AS month_count,
       CAST(COALESCE(SUM(t.amount), 0) AS REAL) AS annual_total
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE c.type = 'expense'
    AND strftime('%Y', t.date) = CAST(?1 AS TEXT)
GROUP BY t.description
HAVING COUNT(DISTINCT strftime('%Y-%m', t.date)) >= 3
ORDER BY annual_total DESC
`

type RecurringDescriptionsRow struct {
	Description string  `json:"description"`
	MonthCount  int64   `json:"month_count"`
	AnnualTotal float64 `json:"annual_total"`
}

// Recurring Expenses
func (q *Queries) RecurringDescriptions(ctx context.Context, year string) ([]RecurringDescriptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, recurringDescriptions, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringDescriptionsRow{}
	for rows.Next() {
		var i RecurringDescriptionsRow
		if err := rows.Scan(&i.Description, &i.MonthCount, &i.AnnualTotal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumByCategoryForMonth = `-- name: SumByCategoryForMonth :many
SELECT c.id, c.name, CAST(COALESCE(SUM(t.amount), 0) AS REAL) AS total
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE c.type = 'expense'
    AND strftime('%Y', t.date) = CAST(?1 AS TEXT)
    AND strftime('%m', t.date) = CAST(?2 AS TEXT)
GROUP BY c.id
ORDER BY total DESC
`

type SumByCategoryForMonthParams struct {
	Year  string `json:"year"`
	Month string `json:"month"`
}

type SumByCategoryForMonthRow struct {
	ID    int64   `json:"id"`
	Name  string  `json:"name"`
	Total float64 `json:"total"`
}

func (q *Queries) SumByCategoryForMonth(ctx context.Context, arg SumByCategoryForMonthParams) ([]SumByCategoryForMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, sumByCategoryForMonth, arg.Year, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumByCategoryForMonthRow{}
	for rows.Next() {
		var i SumByCategoryForMonthRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumByCategoryForRange = `-- name: SumByCategoryForRange :many

SELECT
    c.id,
    c.name,
    c.type AS category_type,
    CAST(strftime('%Y', t.date) AS INTEGER) AS year,
    CAST(strftime('%m', t.date) AS INTEGER) AS month,
    CAST(COALESCE(SUM(t.amount), 0) AS REAL) AS total
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE t.date >= CAST(?1 AS TEXT) AND t.date <= CAST(?2 AS TEXT)
GROUP BY c.id, year, month
ORDER BY c.name, year, month
`

type SumByCategoryForRangeParams struct {
	DateFrom string `json:"date_from"`
	DateTo   string `json:"date_to"`
}

type SumByCategoryForRangeRow struct {
	ID           int64   `json:"id"`
	Name         string  `json:"name"`
	CategoryType string  `json:"category_type"`
	Year         int64   `json:"year"`
	Month        int64   `json:"month"`
	Total        float64 `json:"total"`
}

// Reports
func (q *Queries) SumByCategoryForRange(ctx context.Context, arg SumByCategoryForRangeParams) ([]SumByCategoryForRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, sumByCategoryForRange, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumByCategoryForRangeRow{}
	for rows.Next() {
		var i SumByCategoryForRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CategoryType,
			&i.Year,
			&i.Month,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumByMonthRange = `-- name: SumByMonthRange :many
SELECT
    CAST(strftime('%Y', t.date) AS INTEGER) AS year,
    CAST(strftime('%m', t.date) AS INTEGER) AS month,
    CAST(COALESCE(SUM(CASE WHEN c.type = 'expense' THEN t.amount ELSE 0 END), 0) AS REAL) AS expenses,
    CAST(COALESCE(SUM(CASE WHEN c.type = 'income' THEN t.amount ELSE 0 END), 0) AS REAL) AS income
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE t.date >= CAST(?1 AS TEXT) AND t.date <= CAST(?2 AS TEXT)
GROUP BY year, month
ORDER BY year, month
`

type SumByMonthRangeParams struct {
	DateFrom string `json:"date_from"`
	DateTo   string `json:"date_to"`
}

type SumByMonthRangeRow struct {
	Year     int64   `json:"year"`
	Month    int64   `json:"month"`
	Expenses float64 `json:"expenses"`
	Income   float64 `json:"income"`
}

func (q *Queries) SumByMonthRange(ctx context.Context, arg SumByMonthRangeParams) ([]SumByMonthRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, sumByMonthRange, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumByMonthRangeRow{}
	for rows.Next() {
		var i SumByMonthRangeRow
		if err := rows.Scan(
			&i.Year,
			&i.Month,
			&i.Expenses,
			&i.Income,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumExpensesByDay = `-- name: SumExpensesByDay :many

SELECT t.date, CAST(COALESCE(SUM(t.amount), 0) AS REAL) AS total
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE c.type = 'expense'
    AND strftime('%Y', t.date) = CAST(?1 AS TEXT)
GROUP BY t.date
ORDER BY t.date
`

type SumExpensesByDayRow struct {
	Date  time.Time `json:"date"`
	Total float64   `json:"total"`
}

// Spending Heatmap
func (q *Queries) SumExpensesByDay(ctx context.Context, year string) ([]SumExpensesByDayRow, error) {
	rows, err := q.db.QueryContext(ctx, sumExpensesByDay, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumExpensesByDayRow{}
	for rows.Next() {
		var i SumExpensesByDayRow
		if err := rows.Scan(&i.Date, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumExpensesByDayInMonth = `-- name: SumExpensesByDayInMonth :many

SELECT CAST(strftime('%d', t.date) AS INTEGER) AS day,
       CAST(COALESCE(SUM(t.amount), 0) AS REAL) AS daily_total
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE c.type = 'expense'
    AND strftime('%Y', t.date) = CAST(?1 AS TEXT)
    AND strftime('%m', t.date) = CAST(?2 AS TEXT)
GROUP BY day
ORDER BY day
`

type SumExpensesByDayInMonthParams struct {
	Year  string `json:"year"`
	Month string `json:"month"`
}

type SumExpensesByDayInMonthRow struct {
	Day        int64   `json:"day"`
	DailyTotal float64 `json:"daily_total"`
}

// Expense Velocity
func (q *Queries) SumExpensesByDayInMonth(ctx context.Context, arg SumExpensesByDayInMonthParams) ([]SumExpensesByDayInMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, sumExpensesByDayInMonth, arg.Year, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumExpensesByDayInMonthRow{}
	for rows.Next() {
		var i SumExpensesByDayInMonthRow
		if err := rows.Scan(&i.Day, &i.DailyTotal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumExpensesByMonth = `-- name: SumExpensesByMonth :one

SELECT CAST(COALESCE(SUM(t.amount), 0) AS REAL) AS total
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE c.type = 'expense'
    AND strftime('%Y', t.date) = CAST(?1 AS TEXT)
    AND strftime('%m', t.date) = CAST(?2 AS TEXT)
`

type SumExpensesByMonthParams struct {
	Year  string `json:"year"`
	Month string `json:"month"`
}

// Dashboard aggregation queries
func (q *Queries) SumExpensesByMonth(ctx context.Context, arg SumExpensesByMonthParams) (float64, error) {
	row := q.db.QueryRowContext(ctx, sumExpensesByMonth, arg.Year, arg.Month)
	var total float64
	err := row.Scan(&total)
	return total, err
}

const sumIncomeByMonth = `-- name: SumIncomeByMonth :one
SELECT CAST(COALESCE(SUM(t.amount), 0) AS REAL) AS total
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE c.type = 'income'
    AND strftime('%Y', t.date) = CAST(?1 AS TEXT)
    AND strftime('%m', t.date) = CAST(?2 AS TEXT)
`

type SumIncomeByMonthParams struct {
	Year  string `json:"year"`
	Month string `json:"month"`
}

func (q *Queries) SumIncomeByMonth(ctx context.Context, arg SumIncomeByMonthParams) (float64, error) {
	row := q.db.QueryRowContext(ctx, sumIncomeByMonth, arg.Year, arg.Month)
	var total float64
	err := row.Scan(&total)
	return total, err
}

const topDescriptions = `-- name: TopDescriptions :many
SELECT
    t.description,
    c.type AS category_type,
    COUNT(*) AS tx_count,
    CAST(COALESCE(SUM(t.amount), 0) AS REAL) AS total
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE c.type = 'expense'
    AND t.date >= CAST(?1 AS TEXT) AND t.date <= CAST(?2 AS TEXT)
GROUP BY t.description
ORDER BY total DESC
LIMIT ?3
`

type TopDescriptionsParams struct {
	DateFrom string `json:"date_from"`
	DateTo   string `json:"date_to"`
	Limit    int64  `json:"limit"`
}

type TopDescriptionsRow struct {
	Description  string  `json:"description"`
	CategoryType string  `json:"category_type"`
	TxCount      int64   `json:"tx_count"`
	Total        float64 `json:"total"`
}

func (q *Queries) TopDescriptions(ctx context.Context, arg TopDescriptionsParams) ([]TopDescriptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, topDescriptions, arg.DateFrom, arg.DateTo, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopDescriptionsRow{}
	for rows.Next() {
		var i TopDescriptionsRow
		if err := rows.Scan(
			&i.Description,
			&i.CategoryType,
			&i.TxCount,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transactionAmountsAndTags = `-- name: TransactionAmountsAndTags :many

SELECT t.amount, t.tags
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE c.type = 'expense'
    AND t.tags IS NOT NULL AND t.tags != ''
    AND t.date >= CAST(?1 AS TEXT)
    AND t.date <= CAST(?2 AS TEXT)
`

type TransactionAmountsAndTagsParams struct {
	DateFrom string `json:"date_from"`
	DateTo   string `json:"date_to"`
}

type TransactionAmountsAndTagsRow struct {
	Amount float64        `json:"amount"`
	Tags   sql.NullString `json:"tags"`
}

// Tag Breakdown (raw data for Go-side aggregation)
func (q *Queries) TransactionAmountsAndTags(ctx context.Context, arg TransactionAmountsAndTagsParams) ([]TransactionAmountsAndTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, transactionAmountsAndTags, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransactionAmountsAndTagsRow{}
	for rows.Next() {
		var i TransactionAmountsAndTagsRow
		if err := rows.Scan(&i.Amount, &i.Tags); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :execresult
UPDATE categories
SET name = ?, icon = ?
WHERE id = ?
`

type UpdateCategoryParams struct {
	Name string         `json:"name"`
	Icon sql.NullString `json:"icon"`
	ID   int64          `json:"id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateCategory, arg.Name, arg.Icon, arg.ID)
}

const updateCategoryActive = `-- name: UpdateCategoryActive :execresult
UPDATE categories SET is_active = ? WHERE id = ?
`

type UpdateCategoryActiveParams struct {
	IsActive bool  `json:"is_active"`
	ID       int64 `json:"id"`
}

func (q *Queries) UpdateCategoryActive(ctx context.Context, arg UpdateCategoryActiveParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateCategoryActive, arg.IsActive, arg.ID)
}

const updateCategorySortOrder = `-- name: UpdateCategorySortOrder :exec
UPDATE categories SET sort_order = ? WHERE id = ?
`

type UpdateCategorySortOrderParams struct {
	SortOrder int64 `json:"sort_order"`
	ID        int64 `json:"id"`
}

func (q *Queries) UpdateCategorySortOrder(ctx context.Context, arg UpdateCategorySortOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateCategorySortOrder, arg.SortOrder, arg.ID)
	return err
}

const updateSavedFilter = `-- name: UpdateSavedFilter :execresult
UPDATE saved_filters SET name = ?, filter_json = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
`

type UpdateSavedFilterParams struct {
	Name       string `json:"name"`
	FilterJson string `json:"filter_json"`
	ID         int64  `json:"id"`
	UserID     int64  `json:"user_id"`
}

func (q *Queries) UpdateSavedFilter(ctx context.Context, arg UpdateSavedFilterParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateSavedFilter,
		arg.Name,
		arg.FilterJson,
		arg.ID,
		arg.UserID,
	)
}

const updateTransaction = `-- name: UpdateTransaction :exec
UPDATE transactions
SET date = ?, amount = ?, original_amount = ?, original_currency = ?, description = ?, category_id = ?, tags = ?, notes = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateTransactionParams struct {
	Date             time.Time       `json:"date"`
	Amount           float64         `json:"amount"`
	OriginalAmount   sql.NullFloat64 `json:"original_amount"`
	OriginalCurrency sql.NullString  `json:"original_currency"`
	Description      string          `json:"description"`
	CategoryID       int64           `json:"category_id"`
	Tags             sql.NullString  `json:"tags"`
	Notes            sql.NullString  `json:"notes"`
	ID               int64           `json:"id"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) error {
	_, err := q.db.ExecContext(ctx, updateTransaction,
		arg.Date,
		arg.Amount,
		arg.OriginalAmount,
		arg.OriginalCurrency,
		arg.Description,
		arg.CategoryID,
		arg.Tags,
		arg.Notes,
		arg.ID,
	)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET display_name = ?, role = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateUserParams struct {
	DisplayName string `json:"display_name"`
	Role        string `json:"role"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser, arg.DisplayName, arg.Role, arg.ID)
	return err
}

const upsertBudget = `-- name: UpsertBudget :exec
INSERT INTO budgets (year, month, amount)
VALUES (?, ?, ?)
ON CONFLICT(year, month) DO UPDATE SET
    amount = excluded.amount,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertBudgetParams struct {
	Year   int64   `json:"year"`
	Month  int64   `json:"month"`
	Amount float64 `json:"amount"`
}

func (q *Queries) UpsertBudget(ctx context.Context, arg UpsertBudgetParams) error {
	_, err := q.db.ExecContext(ctx, upsertBudget, arg.Year, arg.Month, arg.Amount)
	return err
}

const upsertCurrency = `-- name: UpsertCurrency :exec
INSERT INTO currencies (code, name, symbol, rate_to_base, is_base)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(code) DO UPDATE SET
    name = excluded.name,
    symbol = excluded.symbol,
    rate_to_base = excluded.rate_to_base,
    is_base = excluded.is_base,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertCurrencyParams struct {
	Code       string  `json:"code"`
	Name       string  `json:"name"`
	Symbol     string  `json:"symbol"`
	RateToBase float64 `json:"rate_to_base"`
	IsBase     bool    `json:"is_base"`
}

func (q *Queries) UpsertCurrency(ctx context.Context, arg UpsertCurrencyParams) error {
	_, err := q.db.ExecContext(ctx, upsertCurrency,
		arg.Code,
		arg.Name,
		arg.Symbol,
		arg.RateToBase,
		arg.IsBase,
	)
	return err
}

const upsertSavingsGoal = `-- name: UpsertSavingsGoal :exec
INSERT INTO savings_goals (year, target_amount)
VALUES (?, ?)
ON CONFLICT(year) DO UPDATE SET
    target_amount = excluded.target_amount,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertSavingsGoalParams struct {
	Year         int64   `json:"year"`
	TargetAmount float64 `json:"target_amount"`
}

func (q *Queries) UpsertSavingsGoal(ctx context.Context, arg UpsertSavingsGoalParams) error {
	_, err := q.db.ExecContext(ctx, upsertSavingsGoal, arg.Year, arg.TargetAmount)
	return err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO app_settings (key, value)
VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET
    value = excluded.value,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting, arg.Key, arg.Value)
	return err
}
