package auth

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"sync"

	"golang.org/x/crypto/bcrypt"
)

// Package-level tunables. These are set via Configure at startup by main;
// tests that don't call Configure get the production defaults below.
//
// The mutex guards against a data race in the unlikely case Configure is
// called concurrently with a request (e.g. a test that reloads config).
var (
	authMu     sync.RWMutex
	bcryptCost = 12 // bcrypt work factor (4-31)
	tokenBytes = 32 // random bytes per session token → 64 hex chars
)

// fallbackDummyHash is a real bcrypt hash (cost 12) of the timing-equalizer
// value. It is the last-resort dummy hash if bcrypt.GenerateFromPassword ever
// fails during (re)configuration, guaranteeing DummyCheckPassword ALWAYS runs a
// real CompareHashAndPassword (a non-trivial bcrypt cost) and never degrades to
// an instant/empty compare that would reopen the user-enumeration timing
// oracle. It never matches any real password.
const fallbackDummyHash = "$2a$12$YW2CmSLfZYUQUJkO3e2PT.V/noJl/ycg5vmPh1A27EjVK9OxMikNK"

func init() {
	// Compute the dummy hash eagerly at the default cost so the very first
	// user-miss after process start pays no extra bcrypt.GenerateFromPassword.
	regenerateDummyHash(bcryptCost)
}

// Configure sets the bcrypt cost and session-token byte length from the
// application config. Safe to call at any time; callers after startup will
// apply to subsequently hashed passwords and generated tokens only.
func Configure(cost, sessionTokenBytes int) {
	authMu.Lock()
	bcryptCost = cost
	tokenBytes = sessionTokenBytes
	authMu.Unlock()
	// Recompute the dummy hash eagerly at the (possibly new) cost so its compare
	// time tracks real wrong-password compares and the work is done now, not on
	// the first user-miss. Note: a real user who registered before an operator
	// raised bcryptCost keeps their original-cost hash (bcrypt embeds the cost
	// per hash), so their compare time diverges from the dummy until they next
	// change their password. This per-user cost divergence is an accepted
	// limitation — it cannot leak existence, only a stale cost.
	regenerateDummyHash(cost)
}

// regenerateDummyHash recomputes dummyHash at the given cost, falling back to a
// hardcoded valid bcrypt hash if generation fails so DummyCheckPassword always
// performs a real compare.
func regenerateDummyHash(cost int) {
	hash, err := bcrypt.GenerateFromPassword([]byte("spendrop-login-timing-equalizer"), cost)
	dummyMu.Lock()
	defer dummyMu.Unlock()
	if err != nil {
		dummyHash = []byte(fallbackDummyHash)
		return
	}
	dummyHash = hash
}

// SetBcryptCostForTesting lowers the bcrypt cost to speed up tests. Kept as a
// backwards-compatible wrapper over Configure so existing test init() funcs
// do not need to change.
func SetBcryptCostForTesting() {
	Configure(4, 32)
}

func HashPassword(password string) (string, error) {
	authMu.RLock()
	cost := bcryptCost
	authMu.RUnlock()
	hash, err := bcrypt.GenerateFromPassword([]byte(password), cost)
	if err != nil {
		return "", fmt.Errorf("hash password: %w", err)
	}
	return string(hash), nil
}

func CheckPassword(hash, password string) bool {
	return bcrypt.CompareHashAndPassword([]byte(hash), []byte(password)) == nil
}

// dummyHash is a bcrypt hash of a throwaway value, used by DummyCheckPassword
// to equalise login timing on the user-miss path. Generated eagerly at init and
// re-generated by Configure at the configured bcryptCost so its compare time
// matches a real wrong-password compare. Never matches any real password.
var (
	dummyMu   sync.RWMutex
	dummyHash []byte
)

// DummyCheckPassword performs a bcrypt comparison against a fixed dummy hash,
// paying the same work as CheckPassword without revealing whether a user
// exists. Always returns false. Callers invoke it on the username-not-found
// branch of login so both 401 paths cost the same. The dummy hash is computed
// eagerly (at init and on Configure), so this never pays an extra
// GenerateFromPassword on the first user-miss and always runs a real
// CompareHashAndPassword (never an instant/empty compare).
func DummyCheckPassword() bool {
	dummyMu.RLock()
	hash := dummyHash
	dummyMu.RUnlock()
	return bcrypt.CompareHashAndPassword(hash, []byte("x")) == nil
}

func GenerateSessionToken() (string, error) {
	authMu.RLock()
	n := tokenBytes
	authMu.RUnlock()
	buf := make([]byte, n)
	if _, err := rand.Read(buf); err != nil {
		return "", fmt.Errorf("generate token: %w", err)
	}
	return hex.EncodeToString(buf), nil
}
